"use strict";

// Original study activities informed by the owner's Component 2 teaching pack.
// Version-specific release permission is recorded separately in content-review.json.
const VERSION = "h446-c2-2026-09-07.1";
function topic(code, title, summary, rows, prerequisites = []) {
  return {
    id: `cs-${code.replaceAll(".", "-")}`, code, title, summary,
    subject: "Computer Science", componentId: "h446-02", contentVersion: VERSION,
    reviewStatus: "review_pending", reviewedBy: null, reviewedAt: null,
    prerequisites, source: "Owner-supplied Component 2 teaching resources; original Neat Notes activities",
    cards: rows.map(([id, objective, category, front, back, distractors, misconception]) => ({
      id, category, front, back, distractors: distractors || [],
      objectives: [`${code}(${objective})`], reviewStatus: "review_pending",
      contentVersion: VERSION, difficulty: /Trace|Apply|Debug/.test(category) ? 2 : 1,
      activityType: /Trace/.test(category) ? "algorithm_trace" : "flashcard",
      commandWord: /^(Explain|Compare|Trace|Identify|Describe|Calculate)/.exec(front)?.[1] || "Recall",
      commonMisconceptions: misconception ? [misconception] : [], prerequisites,
    })),
  };
}
const COMPONENT_TWO_TOPICS = [
  topic("2.1.1", "Thinking abstractly", "Choose the details a model needs, explain its limits and apply abstraction to new situations.", [
    ["abstraction", "a", "Abstraction", "What does abstraction do when modelling a problem?", "It retains details relevant to the purpose and omits unnecessary detail.", ["It divides a problem into separately implemented tasks.", "It represents every real-world detail at maximum precision.", "It replaces a model with its final program code."], "Abstraction and decomposition are different techniques."],
    ["purpose", "b", "Purpose", "Explain how abstraction can make a program easier to develop.", "A smaller set of relevant details reduces the complexity of the model and the code needed to implement it."],
    ["purpose-dependent", "d", "Apply", "A walking route planner and a rail map show the same city. Why might they retain different details?", "Their purposes differ. The walking planner needs usable streets and distances; the rail map needs station connections and interchanges."],
    ["model-limits", "c", "Models", "Why can a model give a result that differs from reality?", "Its assumptions and omitted details may exclude factors that affect the real system.", ["Every model must generate random results.", "A correctly coded model includes all real-world factors.", "The model cannot contain any real measurements."]],
    ["over-abstraction", "c", "Apply", "A journey model ignores all waiting time. When could that make it unsuitable?", "When comparing journeys with different transfers or service frequencies, waiting time could change which route is quickest."],
    ["model-devise", "d", "Apply", "Devise a simple model for finding a cheapest delivery route.", "Represent destinations as nodes, usable roads as edges and delivery costs as weights. Retain restrictions relevant to feasible routes."],
    ["representation", "a", "Representation", "Why is a graph of road connections an abstraction?", "It represents locations and connections while omitting details such as building appearance and road texture.", ["It must include a photograph of every road.", "It turns every road into a separate executable program.", "It removes the connection between every pair of locations."]],
    ["abstraction-cost", "b", "Evaluation", "Does abstraction always make a simulation accurate enough?", "No. The omitted details must be irrelevant to the intended decision; otherwise a simpler model can be misleading."],
  ]),
  topic("2.1.2", "Thinking ahead", "Plan inputs, outputs, preconditions, cached data and reusable components before implementation.", [
    ["input-output", "a", "Apply", "Identify an input and an output for a room-heating controller.", "An input is the measured room temperature; an output is a control signal that switches the heater on or off."],
    ["precondition", "b", "Preconditions", "What is a precondition of an algorithm?", "A condition that must hold before the algorithm is called for its specified behaviour to be guaranteed.", ["A result that is guaranteed after every statement.", "A test that must be repeated after the program terminates.", "A condition that can only be checked by the compiler."]],
    ["binary-precondition", "b", "Apply", "What precondition does binary search require of its input list?", "The list must be sorted according to the same ordering used by the search comparisons.", ["The list must contain an even number of values.", "Every value must be a positive integer.", "The target must already be known to exist."]],
    ["document-contract", "b", "Design", "Why document preconditions alongside inputs and outputs?", "Callers can validate the required conditions and reuse the routine without relying on hidden assumptions."],
    ["cache", "c", "Caching", "What is caching in software?", "Keeping a reusable copy of previously obtained or computed data so it can be retrieved more cheaply later.", ["Deleting frequently requested data after every use.", "Recomputing every result before checking stored values.", "Moving all program variables permanently into ROM."]],
    ["cache-stale", "c", "Evaluation", "Why can a cached result become incorrect for the current situation?", "The underlying data may have changed. Expiry, invalidation or refreshing is needed to manage stale copies."],
    ["cache-tradeoff", "c", "Evaluation", "Explain a cost of caching results that are rarely reused.", "The cache consumes memory and lookup or maintenance work, while providing few avoided computations."],
    ["cache-scenario", "c", "Apply", "Where could caching help a timetable application?", "A recently computed route or fetched timetable could be reused, provided updates invalidate it when services change."],
    ["reusable-module", "d", "Modularity", "Why define a clear interface for a reusable component?", "Other code can supply the expected inputs and use its outputs without depending on its internal implementation."],
    ["reuse-testing", "d", "Evaluation", "Does using a previously tested component remove the need for integration testing?", "No. Its interface, assumptions and behaviour must still be tested in the new system."],
  ], ["cs-2-1-1:abstraction"]),
  topic("2.1.3", "Thinking procedurally", "Decompose problems, order dependent steps and design clear sub-procedures.", [
    ["decomposition", "a", "Decomposition", "What is decomposition?", "Breaking a problem into smaller, manageable sub-problems.", ["Removing every detail from a problem model.", "Executing all instructions at the same instant.", "Repeating a calculation until it reaches a threshold."]],
    ["problem-parts", "a", "Apply", "Decompose the problem of running a library loan service.", "Separate member identification, item availability, loan creation, return processing and overdue reporting."],
    ["solution-parts", "b", "Apply", "Identify components of a solution that calculates a class average from input marks.", "Read marks, validate them, accumulate a total and count, calculate the mean and display it."],
    ["dependency-order", "c", "Sequence", "Why must mark validation happen before an accepted mark contributes to an average?", "Otherwise invalid values can enter the total and make the result incorrect.", ["Validation always changes the order of the input marks.", "Division can only happen in a separate program.", "A total cannot be held in a local variable."]],
    ["subprocedure", "d", "Modularity", "What makes a useful sub-procedure boundary?", "A cohesive task with a clear purpose, defined inputs and outputs, and limited dependence on unrelated state."],
    ["structure-chart", "b", "Representation", "What does a structure diagram show?", "The decomposition of a system into components and subcomponents.", ["The exact elapsed time of each instruction.", "The physical addresses of every variable.", "The truth value of every possible Boolean input."]],
    ["independent-testing", "d", "Testing", "How can decomposition help testing?", "Individual routines can be checked against their contracts before testing their interactions in the complete system."],
    ["empty-average", "c", "Debug", "An average routine divides total by count before checking count. What order is safer?", "First check that count is greater than zero. Only then calculate total divided by count; otherwise handle the empty input."],
  ]),
  topic("2.1.4", "Thinking logically", "Recognise decisions, build Boolean conditions and follow the paths they create.", [
    ["decision-point", "a", "Apply", "Where is a decision needed before removing an item from a queue?", "Check whether the queue is empty before attempting to dequeue.", ["Only after the removed item has been overwritten.", "Before every assignment, regardless of the queue state.", "Only when the queue has exactly two items."]],
    ["compound-condition", "b", "Logic", "A discount requires a valid ticket and age below 18. Which logical connective joins the tests?", "AND, because both conditions must be true.", ["OR, because either condition alone is sufficient.", "NOT, because both tests must be inverted.", "XOR, because exactly one condition must be true."]],
    ["branch-flow", "c", "Flow", "How does IF / ELSE affect program flow?", "It selects one of two paths according to whether the condition is true or false."],
    ["independent-if", "c", "Compare", "How do two independent IF statements differ from IF / ELSE IF?", "Both independent conditions can run their bodies. In an IF / ELSE IF chain, a matched earlier branch prevents later branches in that chain."],
    ["boundary-test", "b", "Debug", "Entry is permitted from age 16. Why is age > 16 an incorrect test?", "It excludes users aged exactly 16. The lower-bound check should include equality, such as age >= 16."],
    ["logic-trace", "b", "Trace", "For age = 17 and hasTicket = false, what is (age < 18) AND hasTicket?", "False: the age comparison is true but hasTicket is false, so the conjunction is false.", ["True, because the age comparison alone is enough.", "True, because AND reverses false operands.", "Undefined, because a Boolean cannot be combined with a comparison."]],
    ["loop-decision", "a", "Iteration", "Which decision controls a condition-controlled loop?", "Whether its continuation or stopping condition has been met; the precise timing depends on the loop form."],
    ["parentheses", "b", "Clarity", "Why use parentheses in a condition mixing AND and OR?", "They make the intended grouping explicit and avoid relying on readers remembering operator precedence."],
  ]),
  topic("2.1.5", "Thinking concurrently", "Separate independent work from dependencies and reason about coordination costs.", [
    ["concurrency", "a", "Concurrency", "How can tasks be concurrent on one processor core?", "Their execution can be interleaved so their lifetimes overlap, even though only one executes at an instant.", ["The core executes every task's instruction at exactly the same instant.", "One task must finish entirely before another can begin.", "Every task must use its own physical computer."]],
    ["parallelism", "a", "Compare", "What distinguishes parallel execution from concurrency alone?", "Parallel tasks execute simultaneously; concurrency also includes interleaved execution."],
    ["independence", "a", "Apply", "Which can be done concurrently: resizing separate photographs or consuming a result that has not yet been calculated?", "Resizing separate photographs can be independent. A step that consumes an unfinished result must wait for its dependency.", ["Only consuming the unfinished result, because it needs no input.", "Neither, because concurrent tasks must share all their data.", "Both without coordination, because dependencies disappear on multiple cores."]],
    ["responsiveness", "b", "Benefits", "How can concurrency improve responsiveness during a slow file operation?", "Other ready work, such as interface updates, can proceed while the file operation waits."],
    ["race", "b", "Risks", "Two bookings read the same final seat as available. What can go wrong?", "Both may sell it before either update is observed. The check-and-update needs atomic coordination to prevent double booking.", ["The seat is guaranteed to remain unsold.", "The two reads automatically cancel both bookings.", "The booking price must become zero."]],
    ["coordination", "b", "Trade-offs", "Why might adding more workers fail to make a program faster?", "Coordination, communication and memory overhead can outweigh parallel work, especially when much of the task is sequential."],
    ["deadlock", "b", "Risks", "How can locks lead to deadlock?", "Tasks can each hold a resource while waiting indefinitely for a resource held by another task in a cycle."],
    ["safe-split", "a", "Apply", "How could a large list be searched concurrently using linear search?", "Partition it into independent regions, search each region, and coordinate the reported results or early termination."],
  ]),
  topic("2.2.1", "Programming techniques", "Trace program constructs, parameters, recursion and object-oriented behaviour; use debugging tools deliberately.", [
    ["constructs", "a", "Constructs", "What are sequence, selection and iteration?", "Sequence runs statements in order, selection chooses paths, and iteration repeats a block."],
    ["pre-post-loop", "a", "Compare", "How do a pre-condition WHILE loop and a post-condition loop differ?", "WHILE can execute zero times if its condition is initially false; a post-condition loop executes its body at least once."],
    ["loop-trace", "a", "Trace", "total = 0; for i = 1 to 3 inclusive: total = total + 2*i. What is total afterwards?", "12, from 2 + 4 + 6.", ["6, from adding the loop counters only.", "10, from omitting the first iteration.", "14, from running one extra addition of 2."]],
    ["recursion", "b", "Recursion", "What must a terminating recursive solution include?", "A reachable base case and recursive steps that make progress towards it.", ["A recursive call with unchanged arguments on every path.", "A global variable for every local value.", "A loop that never changes its condition."]],
    ["factorial-trace", "b", "Trace", "For f(0) = 1 and f(n) = n*f(n-1), calculate f(4).", "24. The calls reduce to f(0), then return through 1, 2, 6 and 24."],
    ["call-stack", "b", "Recursion", "What information is needed to resume a recursive caller?", "A stack frame preserves its return location and relevant local state, including parameters and unfinished work."],
    ["recursion-iteration", "b", "Compare", "Compare recursive and iterative factorial implementations in typical non-optimising environments.", "Both can take linear time. Recursion usually requires a stack frame per call; an iterative loop can reuse a constant amount of auxiliary state."],
    ["scope", "c", "Scope", "Why can two routines each use a local variable named count?", "Each name belongs to its own scope, so their local variables are separate."],
    ["global-risk", "c", "Evaluation", "What maintenance risk comes from writable global variables?", "Unrelated routines can change shared state, making dependencies and the source of unexpected changes harder to trace."],
    ["value", "d", "Parameters", "In pass-by-value, what happens when a routine reassigns its copied scalar parameter?", "The caller's scalar variable is unchanged.", ["The caller's scalar variable is always overwritten.", "The caller's variable is deleted from memory.", "The program must restart before the routine returns."]],
    ["reference", "d", "Parameters", "How does passing a variable by reference differ from passing its scalar value?", "A reference gives access to the caller's variable, so changes through it can affect that original variable."],
    ["function-procedure", "d", "Modularity", "What distinguishes a function from a procedure in the usual OCR pseudocode convention?", "A function returns a value; a procedure carries out a task without returning a value in that way. Functions need not always assign their result to a variable."],
    ["modular-testing", "d", "Design", "Why favour a parameter over reading a global variable in a reusable routine?", "Its dependency is explicit, and it can be tested with different inputs without changing global state."],
    ["breakpoint", "e", "Debugging", "How do a breakpoint and a watch expression help locate a logic error?", "A breakpoint pauses execution at a chosen point; a watch shows relevant values so they can be compared with the expected state."],
    ["step", "e", "Debugging", "Why step through a loop when debugging an off-by-one error?", "Stepping reveals each condition check, index update and iteration, including what happens at the boundaries."],
    ["class-object", "f", "OOP", "How does an object relate to its class?", "An object is an instance with its own state, following the attributes and behaviour defined by the class."],
    ["encapsulation", "f", "OOP", "What is the purpose of encapsulation?", "Keep related state and behaviour together and control access to internal state through an interface."],
    ["inheritance", "f", "OOP", "How can inheritance support reuse?", "A subclass can reuse and extend suitable behaviour and attributes of a superclass."],
    ["polymorphism", "f", "OOP", "What does polymorphism allow when calling the same method on different object types?", "The common interface can invoke different type-specific implementations."],
    ["oop-apply", "f", "Apply", "Why should a BankAccount balance normally be changed through methods rather than direct external writes?", "Methods can enforce rules such as sufficient funds and keep the object's state consistent."],
  ], ["cs-2-1-3:decomposition"]),
  topic("2.2.2", "Computational methods", "Recognise computable tasks and apply decomposition, modelling, heuristics and other problem-solving methods.", [
    ["computable", "a", "Recognition", "What makes a task suitable for a computational solution?", "Its relevant inputs, outputs and processing rules can be represented precisely enough for an algorithm to operate on them."],
    ["problem-recognition", "b", "Recognition", "What should problem recognition establish before choosing an algorithm?", "The actual goal, constraints and success criteria, rather than assuming a particular technical solution."],
    ["decompose", "c", "Decomposition", "How could a timetable problem be decomposed?", "Separate collecting availability, representing constraints, allocating sessions and checking conflicts."],
    ["divide-conquer", "d", "Algorithms", "What are the main stages of divide and conquer?", "Divide into smaller instances, solve those instances and combine their results where required.", ["Read every input once and never split the problem.", "Try a single random answer and stop immediately.", "Remove every constraint before processing any input."]],
    ["merge-method", "d", "Apply", "Why is merge sort an example of divide and conquer?", "It splits the input into smaller lists, sorts them and combines them by merging."],
    ["abstract-model", "e", "Abstraction", "A route planner stores junctions and weighted road connections. What has it abstracted away?", "Details irrelevant to its route objective, such as building colours, while retaining the connections and costs it needs."],
    ["backtracking", "f", "Backtracking", "What does a backtracking algorithm do when a partial solution cannot work?", "It undoes the most recent choice as needed and explores another available choice.", ["It accepts the failed partial solution as optimal.", "It discards all alternative choices permanently.", "It repeats the failed choice without changing state."]],
    ["mining", "f", "Data mining", "What does data mining seek in a large dataset?", "Useful patterns, relationships or anomalies that can inform a decision."],
    ["mining-caution", "f", "Evaluation", "Why does a relationship discovered by data mining not prove causation?", "A correlation may reflect other factors, sampling bias or coincidence; further investigation is needed."],
    ["heuristic", "f", "Heuristics", "Why use a heuristic when exhaustive search is impractical?", "It guides a search or gives a useful approximation within available resources, without necessarily guaranteeing the best answer.", ["It guarantees every possible solution is enumerated.", "It removes the need to define the problem.", "It always produces the optimum result with no assumptions."]],
    ["performance-model", "f", "Modelling", "How can performance modelling help plan a service before launch?", "It estimates behaviour under assumed loads, helping compare capacity options and identify likely bottlenecks."],
    ["model-validation", "f", "Evaluation", "Why should a performance model be checked against measurements?", "Its estimates depend on assumptions; measured behaviour can reveal unrealistic assumptions and improve the model."],
    ["pipeline", "f", "Pipelining", "What is a software processing pipeline?", "A sequence of stages where one stage's output becomes the next stage's input; stages may overlap on different data items."],
    ["pipeline-limit", "f", "Evaluation", "Why does a slow stage limit pipeline throughput?", "Items cannot leave the whole pipeline faster than its bottleneck stage can process them."],
    ["visualisation", "f", "Visualisation", "How can drawing a tree help design a traversal?", "It makes parent-child relationships and possible visit orders visible, helping the programmer trace and check the algorithm."],
    ["intractable", "a", "Complexity", "How is an intractable problem different from an impossible-to-express problem?", "A solution algorithm can be specified, but required resources may be impractical for the input size."],
  ], ["cs-2-1-1:abstraction", "cs-2-1-3:decomposition"]),
  topic("2.3.1", "Algorithms", "Analyse complexity, trace searches and sorts, manipulate data structures and compare shortest-path algorithms.", [
    ["algorithm-contract", "a", "Design", "What should be established before designing an algorithm for a scenario?", "Its inputs, required outputs, constraints and criteria for a correct result."],
    ["boundary-test", "a", "Testing", "Why trace an algorithm with empty, one-item and boundary-value inputs?", "These expose assumptions and off-by-one errors that ordinary cases can miss."],
    ["suitability", "b", "Evaluation", "Why might insertion sort be suitable for a small nearly sorted list?", "It is simple and can do little movement when few elements are out of order, despite quadratic worst-case time."],
    ["big-o", "c", "Complexity", "What does Big O describe?", "An asymptotic upper bound on how a resource requirement grows with input size.", ["An exact runtime in seconds on every computer.", "The number of source-code lines in a program.", "The probability that a program contains a syntax error."]],
    ["log-growth", "c", "Complexity", "Does O(log n) decrease as n increases?", "No. It grows slowly; for base-2 logarithms, doubling n adds one to log2(n)."],
    ["growth-order", "d", "Compare", "Order these growth rates for sufficiently large n: O(n squared), O(1), O(log n), O(2 to the n), O(n).", "O(1), O(log n), O(n), O(n squared), then O(2 to the n)."],
    ["nested-loops", "c", "Trace", "Two nested loops each execute n times with constant work inside. What is the time complexity?", "O(n squared), because the inner work is executed n times for each of n outer iterations.", ["O(n), because both loops use the same bound.", "O(log n), because the code contains two loops.", "O(1), because the source-code length is constant."]],
    ["time-space", "b", "Compare", "How do time complexity and auxiliary space complexity differ?", "Time concerns growth in computational work; auxiliary space concerns additional storage beyond the input representation."],
    ["cases", "d", "Complexity", "Why state best, average or worst case when comparing algorithms?", "Inputs of the same size can require different amounts of work; the chosen case determines what is being compared."],
    ["stack-push", "e", "Data structures", "For an array stack whose top is the occupied top index, initially -1, how is an item pushed?", "Check capacity, increment top, then store the item at array[top]."],
    ["stack-pop", "e", "Trace", "Push A, push B, pop, push C, pop. Which two items are popped?", "B and then C, because the most recently pushed item is removed first."],
    ["queue-circular", "e", "Data structures", "How does a circular array queue reuse positions at the start?", "Advance an index modulo the capacity and track occupancy so full and empty states can be distinguished."],
    ["queue-trace", "e", "Trace", "Enqueue A, enqueue B, dequeue, enqueue C. What is the queue from front to rear?", "B, C."],
    ["linked-insert", "e", "Data structures", "How is a node inserted after a known node in a singly linked list?", "Set the new node's next pointer to the successor, then set the known node's next pointer to the new node."],
    ["linked-delete", "e", "Data structures", "How can a known non-head node be removed from a singly linked list?", "Change its predecessor's next pointer to its successor; reclaim the removed node as appropriate."],
    ["bst-insert", "e", "Trees", "Where is 12 inserted into a binary search tree with root 10 and right child 15, assuming distinct keys?", "As the left child of 15: 12 is greater than 10 but less than 15."],
    ["bst-delete", "e", "Trees", "How can a binary search tree node with two children be deleted while preserving order?", "Replace its key with its in-order successor or predecessor, then remove that replacement node from its original position."],
    ["postorder", "e", "Trace", "A tree has root A with leaf children B (left) and C (right). What is its post-order traversal?", "B, C, A: visit both subtrees before the root.", ["A, B, C: visit the root before both children.", "B, A, C: visit the root between the children.", "C, A, B: visit the right child, root, then left child."]],
    ["breadth", "e", "Trees", "Which structure supports breadth-first traversal and why?", "A queue keeps discovered nodes in first-in-first-out order so earlier levels are processed first."],
    ["linear-search", "f", "Searching", "When can linear search stop?", "When it finds the target, or when all candidate items have been checked."],
    ["binary-trace", "f", "Trace", "Using zero-based inclusive bounds and floor midpoint, trace a search for 17 in [2, 5, 9, 13, 17, 21].", "Check index 2 (9), then index 4 (17); the target is found."],
    ["binary-debug", "a", "Debug", "For an ascending list, midpoint value is smaller than the target. Which bound changes?", "Set low to mid + 1. The target, if present, must be above the midpoint."],
    ["search-complexity", "d", "Compare", "Compare the worst-case time of linear and binary search on an array.", "Linear search is O(n); binary search is O(log n), provided the array is sorted."],
    ["bubble-pass", "f", "Trace", "Perform one left-to-right bubble-sort pass on [4, 1, 3, 2] in ascending order.", "[1, 3, 2, 4]. Each adjacent comparison moves the larger item rightwards."],
    ["bubble-stop", "f", "Sorting", "How can an optimised bubble sort detect it is finished?", "A complete pass with no swaps shows the list is ordered."],
    ["insertion", "f", "Trace", "Insertion sort has sorted prefix [2, 6, 9]; the next key is 4. What is the new prefix?", "[2, 4, 6, 9]. Shift 9 and 6 right, then insert 4 after 2."],
    ["merge", "f", "Trace", "Merge sorted lists [1, 5, 8] and [2, 3, 9].", "[1, 2, 3, 5, 8, 9], repeatedly taking the smaller available leading item."],
    ["merge-complexity", "d", "Complexity", "What is the usual worst-case time complexity of merge sort?", "O(n log n), with O(n) auxiliary storage for a conventional array implementation."],
    ["quick-partition", "f", "Sorting", "What does quicksort's partition step achieve?", "It separates values relative to a pivot so the resulting partitions can be sorted independently."],
    ["quick-worst", "d", "Evaluation", "Why can quicksort have O(n squared) worst-case time?", "Repeated very unbalanced partitions can leave almost the entire list to process at each recursive level."],
    ["dijkstra-init", "f", "Paths", "How are tentative distances initialised for Dijkstra's algorithm?", "Set the start distance to zero and other distances to infinity; use non-negative edge weights."],
    ["dijkstra-relax", "f", "Trace", "Distance to A is 5. Edge A to B costs 3. B currently has distance 10. What update is made?", "Set B's tentative distance to 8 and its predecessor to A, because 5 + 3 is smaller than 10."],
    ["dijkstra-next", "f", "Paths", "Which unvisited node is selected next by Dijkstra's algorithm?", "The node with the smallest tentative total distance from the start."],
    ["astar", "f", "Paths", "In A*, what does f(n) = g(n) + h(n) combine?", "The known cost from the start to n and an estimated remaining cost from n to the goal."],
    ["astar-trace", "f", "Trace", "A* candidates have (g,h): P=(4,7), Q=(8,2), R=(5,8). Which has the lowest f?", "Q, with f = 8 + 2 = 10; P has 11 and R has 13."],
    ["heuristic-guarantee", "f", "Evaluation", "Why does heuristic quality matter in A*?", "It affects search effort and correctness guarantees. A non-overestimating heuristic is needed for standard optimality results, with appropriate handling of revisited nodes."],
    ["path-reconstruct", "f", "Paths", "How is a shortest route reconstructed after distance labels are computed?", "Follow predecessor links backwards from the goal to the start, then reverse that sequence."],
  ], ["cs-2-2-1:recursion", "cs-1-4-2:array"]),
];

module.exports = { COMPONENT_TWO_TOPICS, VERSION };
