(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.RecallPolicies = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  const support = '<a href="mailto:neatnotescontact@gmail.com">neatnotescontact@gmail.com</a>';
  const status = '<p class="policy-review-notice"><strong>Local policy draft, 7 October 2026.</strong> Owner details, provider arrangements and legal terms require review before publication. This text describes the implementation and does not claim legal approval.</p>';
  const pages = {
    privacy: { title: 'Privacy Policy', html: `${status}
      <h3>Who to contact</h3><p>RecallStride is presented as a BreakellSystems product. For privacy questions or requests, contact ${support}. The operator’s full legal identity and postal address must be confirmed before this draft is published.</p>
      <h3>What we use and why</h3><p>We use your name, email, password hash or optional Google account identifier to provide account access, verification and recovery. Your profile, personal notes, revision attempts and preferences support your study workspace and revision suggestions. Subscription identifiers and status determine paid access. Support messages help us respond to enquiries. Session/device details and security records help protect accounts.</p>
      <p>You need an email and an authentication method to use a saved account. You choose what personal text to add to notes. Avoid adding sensitive information or another person’s private details to study text.</p>
      <h3>Coding practice and optional usage measurement</h3><p>Your coding source, virtual files, input fixtures, planning notes and self-review stay in this browser’s account-scoped storage. Guest drafts use separate local storage. They are not sent to the coding API or used as analytics. Local functional outcomes, task/interpreter versions and assistance counters can sync to your account. These outcomes do not produce an OCR mark or verified mastery.</p>
      <p>Usage analytics is off by default. You can change it in Settings. When enabled, coding usage sends only defined event names, task/session identifiers and attempt mode. Disable it to stop future optional event collection; contact support if you want existing events removed. Revision suggestions use your study activity to suggest a next action; they do not predict an exam grade.</p>
      <h3>Processing bases under review</h3><p>The proposed bases are providing the account/subscription service for necessary account and learning operations, consent for optional usage analytics, and legitimate interests for account security and responding to support. Any financial-record legal obligation must be identified precisely. These proposed bases, including their suitability for under-18 users, need legal confirmation and any required balancing assessment before publication.</p>
      <h3>Providers and recipients</h3><p>The existing service is hosted on Render. Stripe handles Checkout, invoices and subscription management when billing is configured; RecallStride stores subscription identifiers and status rather than full payment-card details. Configured email services deliver verification, recovery and support messages. The current support address is a Gmail inbox. Optional Google sign-in shares account identity when you choose it and it is enabled.</p><p>Provider regions, international transfers, safeguards, contracts and support access arrangements remain to be confirmed. Coding execution runs in your browser and does not require an AI provider.</p>
      <h3>How long data remains</h3><p>Account data and notes remain until you delete them or request account deletion; there is currently no automatic inactive-account expiry. Other revision histories have count limits rather than a universal time-based deletion rule. Coding metadata and pilot events expire after 30 days, with cleanup on server startup, use and daily maintenance. Coding drafts stop resuming after 30 days without a saved update and are removed when checked, or when you sign out on that browser. Recall/worked-example drafts also expire after 30 days when checked; mini-mock resume lasts seven days.</p><p>The sign-in cookie lasts up to 30 days. Verification links expire after 24 hours and reset links after 30 minutes; link expiry does not itself erase every database record. Support messages, security/audit logs, billing records and backups need separately approved retention and erasure rules.</p>
      <h3>Your choices, requests and complaints</h3><p>Use Settings to correct your profile and export your account data. The browser export also includes this device’s coding drafts. You can clear coding data in Practice. Account deletion requires confirmation and authentication; active subscriptions and shared/archive ownership can require support handling before the automatic route proceeds. Contact support to resolve a blocked deletion request; the safeguard is not a promise to refuse a lawful request indefinitely.</p><p>You may request access, correction, deletion, restriction or portability where applicable, withdraw analytics consent, and raise an objection to processing based on legitimate interests. Contact ${support} to make a request or challenge a decision. You can also <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noopener">raise a data-protection complaint with the ICO (opens a new tab)</a>.</p>
      <h3>Under-18 users</h3><p>RecallStride is aimed at A-Level students, including people under 18. The current signup form does not verify age or collect parental consent. An age-appropriate explanation, lawful-basis review and decision on any needed parental involvement must be completed before a wider student pilot. No claim of children’s-code compliance is made by this draft.</p>` },
    billing: { title: 'Cancellation and Billing', html: `${status}
      <h3>Free and Pro</h3><p>Free gives access to one published deck selected once. Student Pro is £3.99 billed monthly and renews until cancelled. No annual plan or coding surcharge is offered by this checkout. Published Component 1 and 2 packs are available, but independent academic approval remains outstanding. The coding workspace and its worksheet tasks are available to guests and signed-in students. Separate unfinished revision activities are not included in any plan.</p>
      <h3>Cancel a renewal</h3><p>Sign in, open your account menu and choose Billing to open the Stripe portal. Choose the cancellation option and review its confirmation and effective date. Current portal behaviour needs verification in an approved provider test environment. If you cannot access Billing or your account, contact ${support} with the account email and a payment reference; never send full card details.</p><p>When cancellation is scheduled for the end of an active paid period, paid access continues while the provider reports that subscription as active. At its end the account returns to Free access; your own notes and account export remain accessible. Payment failures can affect paid access. Visiting a checkout success page alone never grants Pro.</p>
      <h3>Refunds and mistakes</h3><p>Cancelling renewal and requesting a refund are separate actions. Contact support about duplicate charges, an unexpected renewal or a service problem so the facts and any applicable statutory rights can be considered. This draft does not set a blanket no-refund policy or promise an unapproved refund window. Digital-service cancellation rights, any immediate-service consent and refund decision rules need legal review before publication.</p>
      <h3>Delete an account</h3><p>Export first, then use Settings → Account → Delete account. Active or past-due subscriptions must be resolved with Billing/support; account deletion does not itself cancel a Stripe subscription or erase provider accounting records. Shared or archived ownership may need an export/ownership arrangement to protect other people’s records. Contact support if the automatic deletion route is blocked.</p>` },
    cookies: { title: 'Cookie and Browser Storage Policy', html: `${status}
      <p>RecallStride uses the essential <code>nn_session</code> cookie for sign-in, with a maximum 30-day life. In production the cookie is HttpOnly, Secure and SameSite=Lax. Optional Google sign-in temporarily uses an OAuth state cookie.</p><p>Browser storage holds preferences, guest work and account-scoped local practice drafts. The service worker caches the public app shell; authenticated API data and gated content remain network-only. Local storage is not encryption. Sign out after using a shared computer and export any coding draft you need before doing so.</p><p>Usage analytics is off by default and controlled in Settings. The coding pilot uses first-party event requests, not a marketing-cookie system. These events contain no coding source, inputs or predictions. The storage/consent classification and the complete cookie inventory require legal review.</p>` },
    terms: { title: 'Terms of Service', html: `${status}
      <p>RecallStride provides independent OCR H446 revision support. It is not endorsed by OCR. Published content is mapped to specification objectives but that mapping does not certify depth, academic approval or readiness for every exam question.</p><p>Written and coding practice offer guided review. A coding program may pass the displayed tests without being correct for every input; the executable dialect is narrower than answers an OCR examiner may credit. No grade prediction is provided.</p><p>Keep your login private and use study features responsibly. Do not place another person’s private information in notes or attempt to disrupt the service. Generic programming practice must not be used to generate candidate-specific assessed NEA project work.</p><p>Subscription availability depends on the active plan and published content. Existing personal notes remain available after a downgrade. Operator identity, age terms, service availability, fair suspension/appeal rules, liability, cancellation rights and governing terms remain to be approved. None of this draft removes statutory consumer rights.</p>` },
    'data-protection': { title: 'Your Account Data', html: `${status}
      <p>Use Settings for profile corrections, JSON account export, device sessions and account deletion. The coding area also exports this device’s source drafts and local outcome history. Sources and predictions are saved locally rather than synced between devices.</p><p>For a blocked deletion, retained support message, backup-erasure question, consent withdrawal or other privacy request, contact ${support}. Backup and provider records need a documented retention/erasure process before this policy can be approved.</p>` }
  };
  return { get(page) { return pages[page] || pages.privacy; } };
});
