window.REVISION_TOPICS = [
  {
    id: "cs-1-1-1",
    subject: "Computer Science",
    code: "1.1.1",
    title: "Structure of the processor",
    source: "NeatNotes1.1.1.pptx",
    summary:
      "CPU components, registers, buses, the fetch-decode-execute cycle, performance factors, pipelining, and processor architectures.",
    cards: [
      {
        id: "cpu-role",
        category: "CPU",
        front: "What is the role of the CPU?",
        back: "The CPU executes program instructions by fetching them from memory, decoding what is required, and executing the operation using its internal components.",
      },
      {
        id: "control-unit",
        category: "Components",
        front: "What does the Control Unit do?",
        back: "It decodes instructions, coordinates the movement of data, sends control signals, and manages the execution of instructions across the processor.",
      },
      {
        id: "alu",
        category: "Components",
        front: "What is the role of the ALU?",
        back: "The Arithmetic Logic Unit performs arithmetic calculations and logical comparisons such as AND, OR, NOT, XOR, greater than, and equal to.",
      },
      {
        id: "register",
        category: "Registers",
        front: "What is a register?",
        back: "A register is a very small, very fast storage location inside the processor used for data or addresses needed immediately by the CPU.",
      },
      {
        id: "accumulator",
        category: "Registers",
        front: "What is the Accumulator used for?",
        back: "The Accumulator temporarily stores data being processed and the results of calculations made by the ALU.",
      },
      {
        id: "program-counter",
        category: "Registers",
        front: "What does the Program Counter store?",
        back: "The Program Counter stores the memory address of the next instruction to be fetched. It usually increments sequentially unless a branch changes it.",
      },
      {
        id: "cir",
        category: "Registers",
        front: "What does the Current Instruction Register hold?",
        back: "The CIR holds the current instruction while it is being decoded and executed, including its opcode and operand.",
      },
      {
        id: "mar",
        category: "Registers",
        front: "What does the Memory Address Register hold?",
        back: "The MAR holds the memory address where data or an instruction is about to be read from or written to.",
      },
      {
        id: "mdr",
        category: "Registers",
        front: "What does the Memory Data Register hold?",
        back: "The MDR holds data that has just been read from memory or is about to be written to memory. It acts as a temporary buffer.",
      },
      {
        id: "fde-cycle",
        category: "FDE Cycle",
        front: "What are the three stages of the fetch-decode-execute cycle?",
        back: "Fetch retrieves the next instruction from memory, decode works out what the instruction means, and execute carries out the instruction.",
      },
      {
        id: "fetch-steps",
        category: "FDE Cycle",
        front: "What key register transfers happen during fetch?",
        back: "The PC value is copied to the MAR, the PC is incremented, memory is read, the instruction travels to the MDR, and the MDR contents are copied to the CIR.",
      },
      {
        id: "decode",
        category: "FDE Cycle",
        front: "What happens during decode?",
        back: "The Control Unit interprets the instruction in the CIR, separates opcode and operand, identifies required hardware, and checks whether extra memory access is needed.",
      },
      {
        id: "execute",
        category: "FDE Cycle",
        front: "What happens during execute?",
        back: "The decoded instruction is carried out. For arithmetic instructions, required data is fetched, the ALU performs the operation, and the result may be stored in the Accumulator.",
      },
      {
        id: "system-bus",
        category: "Buses",
        front: "What are the three buses collectively called?",
        back: "The address bus, data bus, and control bus are collectively called the system bus.",
      },
      {
        id: "address-bus",
        category: "Buses",
        front: "What does the address bus do?",
        back: "The address bus carries the memory address of the location being read from or written to. Its width affects the maximum addressable memory.",
      },
      {
        id: "data-bus",
        category: "Buses",
        front: "What does the data bus do?",
        back: "The data bus carries data and instructions between the CPU, memory, and other components. It is usually bidirectional.",
      },
      {
        id: "control-bus",
        category: "Buses",
        front: "What does the control bus carry?",
        back: "The control bus carries control signals such as memory read, memory write, reset, and interrupt signals between CPU components.",
      },
      {
        id: "performance-factors",
        category: "Performance",
        front: "What three main factors affect processor performance?",
        back: "Clock speed, number of cores, and the amount and type of cache memory are the main OCR performance factors.",
      },
      {
        id: "clock-speed",
        category: "Performance",
        front: "Why can higher clock speed improve performance?",
        back: "A higher clock speed means more cycles per second, so the CPU can begin more operations per second, although some operations take multiple cycles.",
      },
      {
        id: "cache",
        category: "Performance",
        front: "Why does cache improve CPU performance?",
        back: "Cache is very fast memory close to or inside the CPU. Frequently used data and instructions can be fetched from cache instead of slower RAM.",
      },
      {
        id: "cores",
        category: "Performance",
        front: "How can more cores improve performance?",
        back: "More cores allow instructions or programs to be processed in parallel, but the improvement depends on whether the software can use multiple cores effectively.",
      },
      {
        id: "pipelining",
        category: "Pipelining",
        front: "What is pipelining?",
        back: "Pipelining overlaps stages of the FDE cycle, so one instruction can be fetched while another is decoded and another is executed.",
      },
      {
        id: "pipeline-flush",
        category: "Pipelining",
        front: "Why can branch instructions cause problems for pipelining?",
        back: "A branch may change the next instruction address. If the CPU has queued the wrong instruction, the pipeline must be flushed and refilled.",
      },
      {
        id: "von-neumann",
        category: "Architectures",
        front: "How does Von Neumann architecture store data and instructions?",
        back: "Von Neumann architecture stores data and instructions in the same memory and uses the same buses, so it can only fetch one at a time over the shared bus.",
      },
      {
        id: "harvard",
        category: "Architectures",
        front: "How is Harvard architecture different?",
        back: "Harvard architecture has separate memories and buses for data and instructions, allowing both to be fetched in parallel.",
      },
      {
        id: "contemporary",
        category: "Architectures",
        front: "What makes contemporary processors different?",
        back: "Modern processors often combine ideas from Von Neumann and Harvard designs, and may include pipelining, hyper-threading, multiple cores, cache levels, and on-board graphics.",
      },
    ],
  },
  {
    id: "cs-1-1-2",
    subject: "Computer Science",
    code: "1.1.2",
    title: "Types of processor",
    source: "1.1.2 - Topic Notes.pptx",
    summary:
      "Instruction sets, RISC and CISC, parallel processing, GPUs, co-processors, SIMD, SISD, and processor choice for scenarios.",
    cards: [
      {
        id: "instruction-set",
        category: "Instruction Sets",
        front: "What is an instruction set?",
        back: "An instruction set is the complete set of commands a CPU can understand and execute, such as ADD, SUB, LOAD, and STORE.",
      },
      {
        id: "cisc",
        category: "RISC vs CISC",
        front: "What is a CISC processor?",
        back: "A CISC processor has a large set of complex instructions, where one instruction can perform several lower-level operations.",
      },
      {
        id: "risc",
        category: "RISC vs CISC",
        front: "What is a RISC processor?",
        back: "A RISC processor uses a smaller set of simpler instructions, often designed to execute quickly, commonly in a single clock cycle.",
      },
      {
        id: "risc-cisc-task",
        category: "RISC vs CISC",
        front: "How might RISC and CISC differ when multiplying and storing values?",
        back: "CISC may use one complex instruction that loads, multiplies, and stores. RISC would usually combine several simple instructions such as LOAD, MULT, and STORE.",
      },
      {
        id: "risc-mobile",
        category: "Scenarios",
        front: "Why can RISC be suitable for mobile devices?",
        back: "RISC designs can use simpler circuitry, fewer transistors, lower power, and less heat, which suits battery-powered portable devices.",
      },
      {
        id: "cisc-compatibility",
        category: "Scenarios",
        front: "Why might a desktop organisation prefer CISC?",
        back: "CISC may offer stronger compatibility with existing desktop software and complex instruction support, reducing redevelopment costs.",
      },
      {
        id: "parallel-processing",
        category: "Parallelism",
        front: "What is parallel processing?",
        back: "Parallel processing is carrying out multiple computations at the same time, either across CPU cores, multiple CPUs, GPUs, or large systems.",
      },
      {
        id: "multicore",
        category: "Parallelism",
        front: "How can a multicore CPU support parallel processing?",
        back: "A multicore CPU can divide work across separate cores so instructions or tasks can run at the same time where the software supports it.",
      },
      {
        id: "gpu",
        category: "Processors",
        front: "How does a GPU differ from a CPU?",
        back: "A CPU is a general-purpose processor, while a GPU is specialised for highly parallel tasks such as graphics rendering and repeated calculations on large data sets.",
      },
      {
        id: "coprocessor",
        category: "Processors",
        front: "What is a co-processor?",
        back: "A co-processor is an extra specialised processor that supplements the CPU, such as a GPU handling graphics or floating point calculations.",
      },
      {
        id: "simd",
        category: "Architecture",
        front: "What does SIMD mean?",
        back: "Single Instruction Multiple Data: the same instruction is applied to multiple pieces of data simultaneously, which is common in GPUs.",
      },
      {
        id: "sisd",
        category: "Architecture",
        front: "What does SISD mean?",
        back: "Single Instruction Single Data: one instruction is applied to one piece of data at a time, which is the traditional CPU model.",
      },
      {
        id: "gpu-use",
        category: "Scenarios",
        front: "Why are GPUs useful beyond graphics?",
        back: "They are suited to problems where the same calculation is repeated across many data items, such as scientific simulations and some engineering tasks.",
      },
      {
        id: "processor-choice",
        category: "Scenarios",
        front: "What should you weigh when recommending RISC or CISC?",
        back: "Consider battery life, heat, cost, software compatibility, existing systems, performance needs, and whether applications must be redeveloped.",
      },
    ],
  },
  {
    id: "cs-1-1-3",
    subject: "Computer Science",
    code: "1.1.3",
    title: "Input, output and storage",
    source: "1.1.3 - Topic Notes.pptx",
    summary:
      "Input and output devices, RFID, NFC, barcodes, actuators, printer examples, storage media, SSDs, and virtual storage.",
    cards: [
      {
        id: "input-device",
        category: "Input",
        front: "What is an input device?",
        back: "An input device allows data to be entered into a computer, such as a keyboard, scanner, microphone, sensor, RFID reader, or game controller.",
      },
      {
        id: "output-device",
        category: "Output",
        front: "What is an output device?",
        back: "An output device presents processed data from the computer in a human-usable or physical form, such as a screen, printer, speaker, projector, or actuator.",
      },
      {
        id: "rfid",
        category: "Input",
        front: "What is RFID?",
        back: "RFID uses a microchip transponder and antenna to store and transmit an identifier to a reader, often without needing line of sight.",
      },
      {
        id: "active-passive-rfid",
        category: "Input",
        front: "How do active and passive RFID differ?",
        back: "Active RFID tags have their own battery and can transmit over longer distances. Passive RFID tags rely on radio waves from the reader for power.",
      },
      {
        id: "nfc",
        category: "Input",
        front: "How does NFC relate to RFID?",
        back: "NFC extends RFID-style contactless communication but works at very short range, which helps with uses such as phone payments and access control.",
      },
      {
        id: "barcode-qr",
        category: "Input",
        front: "How do linear barcodes and QR codes differ?",
        back: "Linear barcodes store data in one direction, while QR codes are two-dimensional and can store much more information, such as URLs or ticket data.",
      },
      {
        id: "actuator",
        category: "Output",
        front: "What is an actuator?",
        back: "An actuator is an output device that causes physical movement or action, such as opening a valve, starting a pump, moving a wheel, or controlling a smart home device.",
      },
      {
        id: "3d-printer",
        category: "Output",
        front: "Why are 3D printers useful?",
        back: "They can produce prototypes, one-off products, parts, prosthetics, and models by building physical objects from digital designs.",
      },
      {
        id: "accessibility-devices",
        category: "Accessibility",
        front: "Why are specialist input and output devices important?",
        back: "Devices such as eye typers, puff-suck switches, Braille keyboards, screen readers, and voice input help users with different accessibility needs interact with systems.",
      },
      {
        id: "optical-storage",
        category: "Storage",
        front: "How does optical storage work?",
        back: "Optical media such as CDs, DVDs, and Blu-ray use a laser to read pits and lands on a reflective surface.",
      },
      {
        id: "solid-state",
        category: "Storage",
        front: "Why can SSDs be faster and more robust than HDDs?",
        back: "SSDs have no moving parts, so they do not need a spinning disk or read-write head and can access data quickly from flash memory.",
      },
      {
        id: "ssd-tradeoffs",
        category: "Storage",
        front: "What are common SSD trade-offs?",
        back: "SSDs are fast, silent, portable, and power-efficient, but can be more expensive per GB and may have lower capacity than HDDs.",
      },
      {
        id: "virtual-storage",
        category: "Storage",
        front: "What is virtual storage?",
        back: "Virtual storage appears local to the user but is physically stored elsewhere on a network or in the cloud.",
      },
      {
        id: "cloud-benefits",
        category: "Storage",
        front: "What are benefits and risks of cloud storage?",
        back: "Benefits include accessibility, lower hardware cost, and managed backup. Risks include internet dependence, privacy concerns, and trusting a third party with data.",
      },
    ],
  },
  {
    id: "cs-1-2-1",
    subject: "Computer Science",
    code: "1.2.1",
    title: "Operating systems",
    source: "1.2.1 Topic Notes.pptx",
    summary:
      "Operating system functions, OS types, memory management, virtual memory, scheduling, interrupts, BIOS, drivers, and virtual machines.",
    cards: [
      {
        id: "os-definition",
        category: "Operating Systems",
        front: "What is an operating system?",
        back: "An operating system is a program or set of programs that manages computer operations and provides a usable interface between user, software, and hardware.",
      },
      {
        id: "os-functions",
        category: "Operating Systems",
        front: "What are common operating system functions?",
        back: "Providing a user interface, managing hardware and peripherals, managing memory, managing files, scheduling processes, handling interrupts, and supporting security.",
      },
      {
        id: "multitasking",
        category: "OS Types",
        front: "What is a multitasking operating system?",
        back: "A multitasking OS lets a user run more than one task or program apparently at the same time by allocating processor time to each task.",
      },
      {
        id: "multiuser",
        category: "OS Types",
        front: "What is a multi-user operating system?",
        back: "A multi-user OS allows multiple users to use the same computer system at the same time, often through terminals and time slices.",
      },
      {
        id: "distributed",
        category: "OS Types",
        front: "What is a distributed operating system?",
        back: "A distributed OS coordinates multiple computers so they can work together on tasks and appear to the user as one system.",
      },
      {
        id: "embedded",
        category: "OS Types",
        front: "What is an embedded operating system?",
        back: "An embedded OS is built into a device, stored in ROM, and designed for a specific purpose such as a washing machine or heart rate monitor.",
      },
      {
        id: "real-time",
        category: "OS Types",
        front: "What is a real-time operating system?",
        back: "A real-time OS gives guaranteed response times to inputs, making it suitable for safety-critical systems such as aircraft or autonomous vehicles.",
      },
      {
        id: "memory-management",
        category: "Memory",
        front: "What is memory management?",
        back: "Memory management is the allocation and control of RAM by the operating system so programs and data can be stored efficiently while running.",
      },
      {
        id: "virtual-memory",
        category: "Memory",
        front: "What is virtual memory?",
        back: "Virtual memory treats part of secondary storage as extra memory when RAM is limited, but it is slower than physical RAM.",
      },
      {
        id: "scheduling",
        category: "Scheduling",
        front: "Why does an operating system use scheduling?",
        back: "Scheduling manages how much CPU time different processes get, helping ensure fair processing, efficient resource use, and reasonable response times.",
      },
      {
        id: "interrupt",
        category: "Interrupts",
        front: "What is an interrupt?",
        back: "An interrupt is a signal from hardware, software, or a timer that tells the CPU to pause its current work and deal with an event.",
      },
      {
        id: "isr",
        category: "Interrupts",
        front: "What is the role of an interrupt service routine?",
        back: "An ISR is the routine executed to handle an interrupt. The CPU saves register contents, changes the PC to the ISR, then restores state afterwards.",
      },
      {
        id: "bios",
        category: "Booting",
        front: "What does BIOS do?",
        back: "BIOS is stored in ROM and starts the computer by carrying out POST checks, setting up initial hardware, and loading the OS via the bootstrap loader.",
      },
      {
        id: "device-driver",
        category: "Drivers",
        front: "What is a device driver?",
        back: "A device driver is software that lets the operating system communicate with and control a hardware device without knowing the device details.",
      },
      {
        id: "virtual-machine",
        category: "Virtualisation",
        front: "What is a virtual machine?",
        back: "A virtual machine is a software-based computer that shares the host machine's resources and can run a separate operating system or test environment.",
      },
      {
        id: "vm-testing",
        category: "Virtualisation",
        front: "Why are virtual machines useful for testing?",
        back: "They let developers or security experts test software, malware, or OS setups in an isolated environment that can be reset if something goes wrong.",
      },
    ],
  },
  {
    id: "cs-1-2-2",
    subject: "Computer Science",
    code: "1.2.2",
    title: "Applications generation",
    source: "1.2.2 - Topic Notes.pptx",
    summary:
      "Software categories, application software, open and closed source licensing, translators, compilation stages, errors, libraries, linkers, and loaders.",
    cards: [
      {
        id: "software",
        category: "Software",
        front: "What is software?",
        back: "Software is a set of instructions, data, or programs that tell a computer what to do.",
      },
      {
        id: "system-application",
        category: "Software",
        front: "How do system software and application software differ?",
        back: "System software runs and manages the computer, while application software helps users perform tasks such as writing documents, browsing, editing images, or managing accounts.",
      },
      {
        id: "general-special",
        category: "Applications",
        front: "What is the difference between general-purpose and special-purpose software?",
        back: "General-purpose software can be used for many tasks, such as a word processor. Special-purpose software performs one specific task, such as a payroll or booking system.",
      },
      {
        id: "proprietary",
        category: "Licensing",
        front: "What is proprietary software?",
        back: "Proprietary software is owned by an individual or company, protected by copyright and licensing, and usually hides the source code from users.",
      },
      {
        id: "open-source",
        category: "Licensing",
        front: "What is open source software?",
        back: "Open source software makes its source code available so users can inspect, modify, and share it under the rules of its licence.",
      },
      {
        id: "licences",
        category: "Licensing",
        front: "Name common types of software licence.",
        back: "Single-user, multi-user, site licence, concurrent user licence, freeware, shareware, open source, and proprietary licences.",
      },
      {
        id: "translator",
        category: "Translators",
        front: "What is a translator?",
        back: "A translator converts source code into machine code or another executable/intermediate form so the computer can run the program.",
      },
      {
        id: "compiler",
        category: "Translators",
        front: "How does a compiler work?",
        back: "A compiler translates the whole program into object or machine code before execution, producing code that can run without recompiling each time.",
      },
      {
        id: "interpreter",
        category: "Translators",
        front: "How does an interpreter work?",
        back: "An interpreter translates and executes source code line by line each time the program runs.",
      },
      {
        id: "compiler-benefits",
        category: "Translators",
        front: "Why might compiled code be preferred for release software?",
        back: "It can run faster, source code is not distributed, the final object code can be saved, and users do not need the compiler installed.",
      },
      {
        id: "interpreter-benefits",
        category: "Translators",
        front: "Why might interpreted code be useful during development?",
        back: "It can be easier to test and debug because there is no lengthy recompilation after each change, and errors can be reported as lines are executed.",
      },
      {
        id: "assembler",
        category: "Translators",
        front: "What does an assembler do?",
        back: "An assembler translates assembly language mnemonics into machine code for a specific processor instruction set.",
      },
      {
        id: "lexical-analysis",
        category: "Compilation",
        front: "What happens during lexical analysis?",
        back: "Comments and unnecessary whitespace are removed, identifiers and keywords are tokenised, and the symbol table begins to be built.",
      },
      {
        id: "symbol-table",
        category: "Compilation",
        front: "What is the symbol table?",
        back: "The symbol table stores entries for identifiers, keywords, variables, and related information used throughout compilation.",
      },
      {
        id: "optimisation",
        category: "Compilation",
        front: "What is code optimisation?",
        back: "Optimisation improves object code so it may use less memory, run faster, or remove redundant instructions, but it can increase compilation time.",
      },
      {
        id: "syntax-logical",
        category: "Errors",
        front: "How do syntax errors and logical errors differ?",
        back: "Syntax errors break language rules and can be detected by a translator. Logical errors still run but produce incorrect or unintended results.",
      },
      {
        id: "libraries",
        category: "Libraries",
        front: "Why use code libraries?",
        back: "Libraries provide tested reusable routines, save development time, and allow programmers to use functionality they may not want to write from scratch.",
      },
      {
        id: "library-drawbacks",
        category: "Libraries",
        front: "What are drawbacks of using libraries?",
        back: "They can increase compiled file size, require time to learn, introduce dependencies, and may include more routines than the program needs.",
      },
      {
        id: "linker",
        category: "Build Process",
        front: "What does a linker do?",
        back: "A linker combines compiled program code with required library code to produce an executable file or module.",
      },
      {
        id: "loader",
        category: "Build Process",
        front: "What does a loader do?",
        back: "A loader loads the executable module into main memory and allocates the memory space needed for execution.",
      },
    ],
  },
  {
    id: "cs-1-2-3",
    subject: "Computer Science",
    code: "1.2.3",
    title: "Software development",
    source: "1.2.3 - Topic Notes.pptx",
    summary:
      "Project development stages, methodologies, client feedback, Waterfall, Agile, XP, Spiral, RAD, prototyping, and project risk.",
    cards: [
      {
        id: "project-failure",
        category: "Projects",
        front: "Why do IT projects commonly fail?",
        back: "Common reasons include poor leadership, unrealistic timescales, scope creep, poor communication, limited user involvement, weak testing, and poor planning.",
      },
      {
        id: "stages",
        category: "Lifecycle",
        front: "What are the traditional stages of project development?",
        back: "Analysis, design, programming and testing, installation, and evaluation.",
      },
      {
        id: "methodology",
        category: "Methodology",
        front: "What is a software development methodology?",
        back: "A methodology is a structured, agreed framework used to plan, control, and develop a software solution.",
      },
      {
        id: "feedback",
        category: "Users",
        front: "Why is client or user feedback important?",
        back: "Users may not know exactly what they need until they see prototypes. Early feedback can prevent wasted development and help ensure requirements are met.",
      },
      {
        id: "waterfall",
        category: "Waterfall",
        front: "How does the Waterfall model work?",
        back: "Waterfall follows formal documented stages in order, where each stage feeds the next and progress depends on completing the previous stage.",
      },
      {
        id: "waterfall-good",
        category: "Waterfall",
        front: "When is Waterfall suitable?",
        back: "Waterfall suits projects where requirements are clear, stable, well understood, and formal documentation or large team coordination is needed.",
      },
      {
        id: "waterfall-bad",
        category: "Waterfall",
        front: "What are disadvantages of Waterfall?",
        back: "It can be inflexible, user involvement may be limited after the start, and working software appears late so progress can be hard to judge.",
      },
      {
        id: "agile",
        category: "Agile",
        front: "What is the general idea behind Agile development?",
        back: "Agile uses iterative development, frequent feedback, and incremental changes so software can adapt as user requirements become clearer.",
      },
      {
        id: "xp",
        category: "Agile",
        front: "What is Extreme Programming good for?",
        back: "XP supports changing requirements, close user involvement, pair programming, quality code, and frequent checkpoints.",
      },
      {
        id: "xp-drawbacks",
        category: "Agile",
        front: "What are drawbacks of Extreme Programming?",
        back: "It can focus heavily on code over design, may lack defect documentation, and depends on close collaboration between programmers.",
      },
      {
        id: "spiral",
        category: "Spiral",
        front: "How does the Spiral model work?",
        back: "The Spiral model develops software through repeated loops, creating refined prototypes while identifying objectives, managing risk, developing, testing, and planning.",
      },
      {
        id: "spiral-use",
        category: "Spiral",
        front: "When is the Spiral model useful?",
        back: "It is useful for large projects with significant risk because risks are analysed at each stage and prototypes reveal issues early.",
      },
      {
        id: "rad",
        category: "RAD",
        front: "What is Rapid Application Development?",
        back: "RAD is an iterative methodology based on prototypes, user feedback, strict time limits, and reuse of existing components.",
      },
      {
        id: "rad-benefits",
        category: "RAD",
        front: "What are advantages of RAD?",
        back: "It can reduce development time, improve flexibility, encourage customer feedback, and produce working prototypes quickly.",
      },
      {
        id: "rad-drawbacks",
        category: "RAD",
        front: "What are possible drawbacks of RAD?",
        back: "It may need strong user involvement, can produce weaker documentation, and may not suit projects where requirements must be formally fixed early.",
      },
      {
        id: "evaluation",
        category: "Lifecycle",
        front: "What is evaluated at the end of development?",
        back: "The finished system is judged against requirements: whether it solves the problem, is effective, and meets the user's expectations.",
      },
    ],
  },
  {
    id: "cs-1-2-4",
    subject: "Computer Science",
    code: "1.2.4",
    title: "Types of programming language",
    source: "1.2.4 - Topic Notes.pptx",
    summary:
      "Assembly language, LMC tracing, instruction words, opcodes, operands, immediate, direct, indirect and indexed addressing, and programming paradigms.",
    cards: [
      {
        id: "assembly-language",
        category: "Assembly",
        front: "What is assembly language?",
        back: "Assembly language is a low-level language that uses mnemonics to represent machine-code instructions for a specific processor instruction set.",
      },
      {
        id: "assembler",
        category: "Translation",
        front: "What does an assembler do?",
        back: "An assembler translates assembly language into machine code that the processor can execute.",
      },
      {
        id: "instruction-set",
        category: "Assembly",
        front: "Why is assembly language processor-specific?",
        back: "Assembly language depends on the instruction set of a particular processor, so mnemonics and available operations can differ between architectures.",
      },
      {
        id: "mnemonic",
        category: "Assembly",
        front: "What is a mnemonic in assembly language?",
        back: "A mnemonic is a short memorable code, such as LDA or SUB, used to represent a machine-code opcode.",
      },
      {
        id: "word-opcode-operand",
        category: "Instructions",
        front: "What are the opcode and operand in an instruction word?",
        back: "The opcode tells the processor which operation to perform. The operand gives the value or address the operation uses.",
      },
      {
        id: "instruction-word",
        category: "Instructions",
        front: "What is an instruction word?",
        back: "An instruction word is a fixed-size group of bits handled by the processor as one instruction, often split into opcode and operand fields.",
      },
      {
        id: "accumulator",
        category: "LMC",
        front: "What is the accumulator used for in LMC-style programs?",
        back: "The accumulator temporarily stores data while instructions input, load, add, subtract, store, and output values.",
      },
      {
        id: "lmc-sequence",
        category: "LMC",
        front: "What does the LMC sequence input, store, input, add, subtract, output usually show?",
        back: "It shows how values move through the accumulator and named memory locations while a simple arithmetic algorithm is traced step by step.",
      },
      {
        id: "dat",
        category: "LMC",
        front: "What is DAT used for in LMC?",
        back: "DAT reserves a labelled memory location for data, optionally with a starting value.",
      },
      {
        id: "branching",
        category: "Branching",
        front: "Why are branch instructions important in assembly-style code?",
        back: "Branch instructions change the flow of execution, allowing programs to repeat, skip code, or choose a path based on accumulator conditions.",
      },
      {
        id: "brz",
        category: "Branching",
        front: "What does a zero branch test do?",
        back: "It branches to a labelled instruction when the accumulator value is zero, which is useful for equality tests and loop exits.",
      },
      {
        id: "repeated-subtraction",
        category: "Algorithms",
        front: "How can division be modelled when there is no divide instruction?",
        back: "A program can repeatedly subtract the divisor from the dividend and count how many successful subtractions occur, ignoring any remainder.",
      },
      {
        id: "immediate-addressing",
        category: "Addressing",
        front: "What is immediate addressing?",
        back: "Immediate addressing uses the operand as the actual value to be operated on, so RAM is not accessed to fetch that value.",
      },
      {
        id: "direct-addressing",
        category: "Addressing",
        front: "What is direct addressing?",
        back: "Direct addressing uses the operand as the memory address where the required data is stored.",
      },
      {
        id: "indirect-addressing",
        category: "Addressing",
        front: "What is indirect addressing?",
        back: "Indirect addressing uses the operand as the location that stores the address of the required data, allowing a wider addressable range.",
      },
      {
        id: "indexed-addressing",
        category: "Addressing",
        front: "What is indexed addressing used for?",
        back: "Indexed addressing adds an index register to a base address, making it useful for accessing arrays stored in contiguous memory locations.",
      },
      {
        id: "paradigm",
        category: "Paradigms",
        front: "What is a programming paradigm?",
        back: "A programming paradigm is a style or way of programming that shapes how a problem is modelled and solved.",
      },
      {
        id: "procedural",
        category: "Paradigms",
        front: "What is procedural programming?",
        back: "Procedural programming uses modules and the constructs sequence, selection, iteration, and recursion to break problems into manageable routines.",
      },
      {
        id: "object-oriented",
        category: "Paradigms",
        front: "What ideas define object-oriented programming?",
        back: "Object-oriented programming uses classes, objects, methods, attributes, encapsulation, inheritance, and polymorphism to model reusable software.",
      },
      {
        id: "declarative",
        category: "Paradigms",
        front: "What is declarative programming?",
        back: "Declarative programming describes the desired result or facts about a problem, while the language implementation decides how to produce the answer.",
      },
    ],
  },
  {
    id: "cs-1-3-1",
    subject: "Computer Science",
    code: "1.3.1",
    title: "Compression, encryption and hashing",
    source: "1.3.1 Topic Notes.pptx",
    summary:
      "Lossy and lossless compression, run-length encoding, dictionary coding, encryption, symmetric and asymmetric keys, hashing, collisions, rainbow tables, salts, and checksums.",
    cards: [
      {
        id: "compression",
        category: "Compression",
        front: "What is compression?",
        back: "Compression uses an algorithm to make a file's storage size smaller.",
      },
      {
        id: "why-compress",
        category: "Compression",
        front: "Why do we compress files?",
        back: "Compressed files download faster, use less bandwidth, cost users less data, and save storage space on servers and devices.",
      },
      {
        id: "lossy",
        category: "Compression",
        front: "What is lossy compression?",
        back: "Lossy compression reduces file size by permanently removing some data, so the original cannot be perfectly restored.",
      },
      {
        id: "lossless",
        category: "Compression",
        front: "What is lossless compression?",
        back: "Lossless compression reduces file size without losing data, so the original can be reconstructed exactly.",
      },
      {
        id: "rle",
        category: "Compression",
        front: "How does run-length encoding work?",
        back: "RLE replaces consecutive repeated symbols with the symbol and the number of times it occurs, such as AAAABBB becoming A4B3.",
      },
      {
        id: "dictionary",
        category: "Compression",
        front: "How does dictionary coding work?",
        back: "Frequently occurring strings or data groups are replaced with shorter tokens, and a dictionary maps each token back to the original data.",
      },
      {
        id: "encryption",
        category: "Encryption",
        front: "What is encryption?",
        back: "Encryption converts data into coded form to prevent unauthorised access.",
      },
      {
        id: "symmetric",
        category: "Encryption",
        front: "What is symmetric encryption?",
        back: "Symmetric encryption uses the same key to encrypt and decrypt data, so both parties need a secure copy of the key.",
      },
      {
        id: "asymmetric",
        category: "Encryption",
        front: "What is asymmetric encryption?",
        back: "Asymmetric encryption uses a public key for encryption and a different private key for decryption, avoiding the need to share the private key.",
      },
      {
        id: "key-length",
        category: "Encryption",
        front: "Why does encryption key length matter?",
        back: "A longer key creates many more possible combinations, making brute-force cracking much harder.",
      },
      {
        id: "hash",
        category: "Hashing",
        front: "What is a hash?",
        back: "A hash is the result of applying a hashing algorithm to data, producing a fixed or smaller representation that cannot feasibly be reversed.",
      },
      {
        id: "hash-password",
        category: "Hashing",
        front: "Why store password hashes instead of passwords?",
        back: "If a database is accessed, attackers see hashes rather than plaintext passwords, reducing the risk of direct password theft.",
      },
      {
        id: "good-hash",
        category: "Hashing",
        front: "What makes a good hashing algorithm?",
        back: "It should be quick to calculate, have a low chance of collisions, and produce very different outputs for tiny input changes.",
      },
      {
        id: "rainbow",
        category: "Hashing",
        front: "What is a rainbow table?",
        back: "A rainbow table stores precomputed plaintext and hash pairs so attackers can look up possible original passwords from hashes.",
      },
      {
        id: "salt",
        category: "Hashing",
        front: "How does adding salt improve password security?",
        back: "A random salt is added to the password before hashing, making precomputed hash tables much less useful.",
      },
      {
        id: "checksum",
        category: "Hashing",
        front: "How can hashing verify files?",
        back: "A checksum or hash can be recalculated and compared to the expected value to check whether software or data has changed.",
      },
    ],
  },
  {
    id: "cs-1-3-2",
    subject: "Computer Science",
    code: "1.3.2",
    title: "Databases",
    source: "1.3.2 - Topic Notes.pptx",
    summary:
      "SQL, databases, data capture, APIs and exchange formats, relational databases, keys, referential integrity, indexing, ERDs, record locking, ACID, and normalisation.",
    cards: [
      {
        id: "database",
        category: "Basics",
        front: "What is a database?",
        back: "A database is a structured collection of related data, often made up of one or more tables.",
      },
      {
        id: "table-record-field",
        category: "Basics",
        front: "What are tables, records, and fields?",
        back: "A table stores related data. A record is one row in a table. A field is one category or column of data.",
      },
      {
        id: "sql-keywords",
        category: "SQL",
        front: "What do SELECT, FROM, and WHERE do in SQL?",
        back: "SELECT chooses the fields to show, FROM chooses the table, and WHERE filters records using criteria.",
      },
      {
        id: "order-by",
        category: "SQL",
        front: "What is ORDER BY used for?",
        back: "ORDER BY sorts query results, commonly in ascending or descending order.",
      },
      {
        id: "api",
        category: "Data Exchange",
        front: "What is an API?",
        back: "An Application Programming Interface is a prewritten set of interfaces or subroutines that allows programmers to access or exchange data between systems.",
      },
      {
        id: "csv-json-xml",
        category: "Data Exchange",
        front: "How do CSV, JSON, and XML differ?",
        back: "CSV separates values with commas, JSON represents data as JavaScript-style objects, and XML uses tags to structure data.",
      },
      {
        id: "relational",
        category: "Relational Databases",
        front: "What is a relational database?",
        back: "A relational database stores data in multiple related tables connected using keys.",
      },
      {
        id: "join",
        category: "Relational Databases",
        front: "What does an INNER JOIN do?",
        back: "An INNER JOIN combines records from two tables where a shared key or field matches in both tables.",
      },
      {
        id: "primary-key",
        category: "Keys",
        front: "What is a primary key?",
        back: "A primary key is a field with a unique value used to identify each record in a table.",
      },
      {
        id: "foreign-key",
        category: "Keys",
        front: "What is a foreign key?",
        back: "A foreign key is a field that links to a primary key in another table.",
      },
      {
        id: "secondary-key",
        category: "Keys",
        front: "What is a secondary key?",
        back: "A secondary key is a field likely to be searched and indexed to make searches faster.",
      },
      {
        id: "referential-integrity",
        category: "Integrity",
        front: "What is referential integrity?",
        back: "Referential integrity ensures linked data remains consistent, so a foreign key value must match a valid primary key and cascaded changes are handled correctly.",
      },
      {
        id: "flat-file",
        category: "Database Design",
        front: "What problems can flat file databases cause?",
        back: "They can repeat data, waste space, make updates harder, and lead to inconsistent data if the same fact is stored in several places.",
      },
      {
        id: "relational-benefits",
        category: "Database Design",
        front: "Why use a relational database?",
        back: "It reduces duplication, improves consistency and integrity, can improve security, and makes it easier to change related data structures.",
      },
      {
        id: "indexing",
        category: "Searching",
        front: "What is indexing in a database?",
        back: "An index stores key positions so indexed fields can be searched more quickly, but it takes extra space and must be updated when data changes.",
      },
      {
        id: "many-to-many",
        category: "ERD",
        front: "Why must many-to-many relationships be resolved?",
        back: "A fully normalised relational database cannot directly store many-to-many relationships efficiently, so a linking table is introduced between the entities.",
      },
      {
        id: "record-locking",
        category: "Transactions",
        front: "What is record locking?",
        back: "Record locking allows only one user or process to modify a record at a time so simultaneous transactions do not overwrite each other.",
      },
      {
        id: "deadlock",
        category: "Transactions",
        front: "What is deadlock?",
        back: "Deadlock happens when two or more processes block each other because each holds a locked resource the other needs.",
      },
      {
        id: "transaction",
        category: "Transactions",
        front: "What is transaction processing?",
        back: "Transaction processing groups multiple smaller operations into one transaction so the whole operation completes or fails together.",
      },
      {
        id: "acid",
        category: "Transactions",
        front: "What does ACID stand for?",
        back: "Atomicity, Consistency, Isolation, and Durability.",
      },
      {
        id: "normalisation",
        category: "Normalisation",
        front: "Why normalise a database?",
        back: "Normalisation divides data into multiple tables to reduce redundancy, inconsistency, and improve data integrity.",
      },
      {
        id: "normal-forms",
        category: "Normalisation",
        front: "What are 1NF, 2NF, and 3NF?",
        back: "1NF has atomic data, no repeating fields, and a primary key. 2NF means every field depends on the primary key. 3NF means fields depend on the key, the whole key, and nothing but the key.",
      },
    ],
  },
  {
    id: "cs-1-3-3",
    subject: "Computer Science",
    code: "1.3.3",
    title: "Networks, standards and protocols",
    source: "1.3.3 - Topic Notes COPY.pptx",
    summary:
      "Networks, protocols, standards, IP and MAC addresses, DNS, LANs, WANs, packets, switching, TCP/IP layers, network hardware, security, threats, and network models.",
    cards: [
      {
        id: "network",
        category: "Networks",
        front: "What is a computer network?",
        back: "A network is two or more computers or devices connected so they can exchange information and share resources.",
      },
      {
        id: "network-benefits",
        category: "Networks",
        front: "What can a network provide?",
        back: "File sharing, resource sharing, data protection, redundancy, easier administration, distributed computing power, and internal communication.",
      },
      {
        id: "protocol",
        category: "Protocols",
        front: "What is a protocol?",
        back: "A protocol is a set of rules governing data transmission so devices can communicate and interpret data consistently.",
      },
      {
        id: "standards",
        category: "Standards",
        front: "Why are computing standards useful?",
        back: "Standards make software, files, and hardware more compatible across systems, countries, and manufacturers.",
      },
      {
        id: "ip-address",
        category: "Addressing",
        front: "What is an IP address?",
        back: "An IP address is a logical identifier for a device on a network and can change depending on the network connection.",
      },
      {
        id: "mac-address",
        category: "Addressing",
        front: "What is a MAC address?",
        back: "A MAC address is a physical identifier assigned to a network interface card, usually written as 12 hexadecimal digits.",
      },
      {
        id: "dns",
        category: "Internet",
        front: "What does DNS do?",
        back: "The Domain Name System translates human-readable domain names into IP addresses so browsers can locate servers.",
      },
      {
        id: "lan-wan",
        category: "Networks",
        front: "How do LANs and WANs differ?",
        back: "A LAN covers a small geographical area and is usually privately owned. A WAN covers a large area and may use third-party infrastructure.",
      },
      {
        id: "packet",
        category: "Packets",
        front: "What are the main parts of a packet?",
        back: "A packet usually contains a header with addressing and sequence data, a payload containing the data, and a trailer with error checking such as a checksum.",
      },
      {
        id: "packet-switching",
        category: "Switching",
        front: "How does packet switching work?",
        back: "Data is split into packets that can travel by different routes across the network and are reassembled at the destination.",
      },
      {
        id: "packet-benefits",
        category: "Switching",
        front: "What are benefits of packet switching?",
        back: "It uses network channels efficiently, makes interception harder, and allows damaged packets to be retransmitted without resending everything.",
      },
      {
        id: "circuit-switching",
        category: "Switching",
        front: "How does circuit switching work?",
        back: "A dedicated connection path is established for the whole communication, data is transferred, then the connection is released.",
      },
      {
        id: "tcpip",
        category: "TCP/IP",
        front: "What are the four TCP/IP layers?",
        back: "Application, Transport, Internet, and Link.",
      },
      {
        id: "application-layer",
        category: "TCP/IP",
        front: "What happens at the application layer?",
        back: "Application protocols such as HTTP, HTTPS, SMTP, and IMAP operate here, handling the user's network application data.",
      },
      {
        id: "transport-layer",
        category: "TCP/IP",
        front: "What happens at the transport layer?",
        back: "TCP establishes end-to-end communication, splits data into packets, labels them with sequence and port data, and handles acknowledgements or retransmission.",
      },
      {
        id: "internet-layer",
        category: "TCP/IP",
        front: "What happens at the internet layer?",
        back: "Source and destination IP addresses are added and routers use them to forward packets across networks.",
      },
      {
        id: "link-layer",
        category: "TCP/IP",
        front: "What happens at the link layer?",
        back: "The link layer works with network hardware and MAC addresses to move data between directly connected network nodes.",
      },
      {
        id: "layering",
        category: "TCP/IP",
        front: "Why is protocol layering useful?",
        back: "Layers can be developed independently, upgraded separately, and combined with layers from different providers.",
      },
      {
        id: "router",
        category: "Hardware",
        front: "What does a router do?",
        back: "A router passes data between networks by reading packet IP addresses and forwarding packets along a suitable route.",
      },
      {
        id: "switch-hub",
        category: "Hardware",
        front: "How does a switch differ from a hub?",
        back: "A switch inspects packets and forwards them to the correct device, while a hub broadcasts data to all connected devices.",
      },
      {
        id: "proxy",
        category: "Security",
        front: "What is a proxy server used for?",
        back: "A proxy can intercept network traffic, hide internal addresses, cache common websites, and filter requests.",
      },
      {
        id: "firewall",
        category: "Security",
        front: "What does a firewall do?",
        back: "A firewall monitors and filters packets entering or leaving a network to help prevent unauthorised access.",
      },
      {
        id: "ddos",
        category: "Threats",
        front: "What is a DDoS attack?",
        back: "A distributed denial-of-service attack uses many compromised devices to overwhelm a service so legitimate users cannot access it.",
      },
      {
        id: "client-server-p2p",
        category: "Network Models",
        front: "How do client-server and peer-to-peer networks differ?",
        back: "Client-server networks centralise services and administration around servers. Peer-to-peer networks give devices equal status with no central server.",
      },
    ],
  },
  {
    id: "cs-1-3-4",
    subject: "Computer Science",
    code: "1.3.4",
    title: "Web technologies",
    source: "1.3.4 - Topic Notes.pptx",
    summary:
      "HTML, CSS, forms, identifiers, JavaScript validation, search engine indexing, metadata, PageRank, SEO, and server-side processing.",
    cards: [
      {
        id: "html",
        category: "HTML",
        front: "What is HTML used for?",
        back: "HTML defines the structure and content of a web page, such as headings, paragraphs, lists, links, images, and forms.",
      },
      {
        id: "css",
        category: "CSS",
        front: "What is CSS used for?",
        back: "CSS controls the presentation of web pages, including colour, layout, font, spacing, and responsive styling.",
      },
      {
        id: "forms",
        category: "HTML",
        front: "Why are HTML forms used?",
        back: "Forms collect user input, such as names, email addresses, passwords, radio selections, checkboxes, and submitted data.",
      },
      {
        id: "id-selector",
        category: "CSS",
        front: "What is an HTML identifier used for?",
        back: "An id uniquely identifies an element on a page and can be targeted in CSS using a hash selector such as #myHeader.",
      },
      {
        id: "client-validation",
        category: "JavaScript",
        front: "Why use JavaScript to validate input before submission?",
        back: "Client-side validation can catch erroneous data before it reaches the server, improving user feedback and reducing unnecessary server processing.",
      },
      {
        id: "javascript-output",
        category: "JavaScript",
        front: "How can JavaScript change a web page?",
        back: "JavaScript can respond to events, process input, and change the contents or attributes of HTML elements dynamically.",
      },
      {
        id: "crawler",
        category: "Search",
        front: "What does a search engine crawler do?",
        back: "A crawler visits websites, records key text and metadata, follows links, and stores information in a search index.",
      },
      {
        id: "indexed-words",
        category: "Search",
        front: "What kinds of words can crawlers collect from a page?",
        back: "Main content, headings, metadata, image alt text, anchor text, URL words, and user-generated text such as comments.",
      },
      {
        id: "metadata",
        category: "Search",
        front: "What is metadata on a web page?",
        back: "Metadata is data about the page, such as meta descriptions and keywords, which search engines can use to understand the content.",
      },
      {
        id: "pagerank",
        category: "Search",
        front: "What is PageRank?",
        back: "PageRank is a score that estimates a web page's importance based on the quality and quantity of links to it.",
      },
      {
        id: "pagerank-factors",
        category: "Search",
        front: "What factors affect PageRank?",
        back: "The number of pages linking to the site, the PageRank of those linking pages, and the number of outward links from those pages.",
      },
      {
        id: "seo",
        category: "Search",
        front: "What is SEO?",
        back: "Search Engine Optimisation is a set of techniques used to increase a site's visibility in search results.",
      },
      {
        id: "seo-techniques",
        category: "Search",
        front: "Give examples of SEO techniques.",
        back: "Use relevant keywords, meaningful URLs and filenames, meta tags, useful page text, backlinks, directories, social sharing, and link exchanges.",
      },
      {
        id: "server-side",
        category: "Processing",
        front: "What is server-side processing?",
        back: "Server-side processing sends data from the browser to a web server, where code runs and returns a response to the client.",
      },
      {
        id: "server-side-benefits",
        category: "Processing",
        front: "What are benefits of server-side processing?",
        back: "It hides code from users, can access secure data, avoids relying on the browser having the right interpreter, and is useful for generated content.",
      },
      {
        id: "server-side-drawbacks",
        category: "Processing",
        front: "What are drawbacks of server-side processing?",
        back: "It puts extra load on the server and any submitted data must be checked carefully before processing.",
      },
    ],
  },
  {
    id: "cs-1-4-1",
    subject: "Computer Science",
    code: "1.4.1",
    title: "Data types",
    source: "1.4.1 - Topic Notes.pptx",
    summary:
      "Variables, constants, primitive data types, casting, number bases, binary arithmetic, negative numbers, shifts, masks, units, character sets, and floating point representation.",
    cards: [
      {
        id: "variables",
        category: "Programming Data",
        front: "What is a variable?",
        back: "A variable is an identifier given to a memory location whose value can change while a program is running.",
      },
      {
        id: "constants",
        category: "Programming Data",
        front: "What is a constant?",
        back: "A constant is a named value that does not change while the program is running, such as PI in a circle-area calculation.",
      },
      {
        id: "naming-conventions",
        category: "Programming Data",
        front: "Why use naming conventions for variables and constants?",
        back: "Consistent naming makes code easier to read, reduces confusion, and helps distinguish constants, often written in uppercase, from variables.",
      },
      {
        id: "primitive-types",
        category: "Data Types",
        front: "Name common primitive data types.",
        back: "Integer, real or floating point, character, string, and Boolean are common primitive data types.",
      },
      {
        id: "integer-real",
        category: "Data Types",
        front: "How do integer and real data types differ?",
        back: "An integer stores whole numbers. A real or floating-point value stores decimal numbers or very large and very small values.",
      },
      {
        id: "character-string",
        category: "Data Types",
        front: "How do character and string data types differ?",
        back: "A character stores one letter, digit, or symbol. A string stores a sequence of characters enclosed in quote marks.",
      },
      {
        id: "boolean",
        category: "Data Types",
        front: "What can a Boolean value store?",
        back: "A Boolean value stores one of two logical states: true or false.",
      },
      {
        id: "casting-parsing",
        category: "Data Types",
        front: "What are casting and parsing?",
        back: "They are processes for changing data from one type to another, such as converting the string \"2\" into the integer 2.",
      },
      {
        id: "number-bases",
        category: "Number Bases",
        front: "What bases do denary, binary, and hexadecimal use?",
        back: "Denary uses base 10, binary uses base 2, and hexadecimal uses base 16 with digits 0-9 and letters A-F.",
      },
      {
        id: "hex-nibble",
        category: "Number Bases",
        front: "Why does hexadecimal pair neatly with binary?",
        back: "Each hexadecimal digit represents exactly four bits, so a byte can be written as two hexadecimal digits.",
      },
      {
        id: "binary-addition",
        category: "Binary Arithmetic",
        front: "What should be shown in binary addition exam questions?",
        back: "You should show the carry bits clearly and discard overflow if the result exceeds the available number of bits.",
      },
      {
        id: "sign-magnitude",
        category: "Negative Numbers",
        front: "How does sign and magnitude represent negative numbers?",
        back: "The most significant bit stores the sign, usually 0 for positive and 1 for negative, while the remaining bits store the magnitude.",
      },
      {
        id: "twos-complement",
        category: "Negative Numbers",
        front: "How do you convert a positive binary number into negative two's complement?",
        back: "Write the positive binary value, flip every bit, then add 1.",
      },
      {
        id: "binary-subtraction",
        category: "Binary Arithmetic",
        front: "How can binary subtraction be performed using two's complement?",
        back: "Convert the second number into its negative two's complement form, then add it to the first number and ignore any overflow.",
      },
      {
        id: "left-shift",
        category: "Shifts",
        front: "What does a left shift do to an unsigned binary number?",
        back: "A left shift moves bits left, adds zeros on the right, and multiplies the value by 2 for each place shifted.",
      },
      {
        id: "right-shift",
        category: "Shifts",
        front: "What does a right shift do to an unsigned binary number?",
        back: "A right shift moves bits right, adds zeros on the left, and divides the value by 2 for each place shifted.",
      },
      {
        id: "binary-mask",
        category: "Masks",
        front: "What is a binary mask?",
        back: "A binary mask combines an original byte with a mask value using a logic operation such as AND, OR, or XOR.",
      },
      {
        id: "mask-rules",
        category: "Masks",
        front: "What are the AND, OR, and XOR mask rules?",
        back: "AND outputs 1 only when both bits are 1. OR outputs 1 when at least one bit is 1. XOR outputs 1 when exactly one bit is 1.",
      },
      {
        id: "bits-bytes-nibbles",
        category: "Storage Units",
        front: "How are bits, nibbles, and bytes related?",
        back: "A bit is one binary digit, a nibble is four bits, and a byte is eight bits.",
      },
      {
        id: "n-bit-values",
        category: "Storage Units",
        front: "How many values can n bits represent?",
        back: "n bits can represent 2 to the power of n different values.",
      },
      {
        id: "kibi-kilo",
        category: "Storage Units",
        front: "How do kilo and kibi differ in data measurement?",
        back: "Kilo refers to 1000, while kibi refers to 1024 and is used for binary-based storage units such as KiB.",
      },
      {
        id: "ascii",
        category: "Character Sets",
        front: "What is ASCII?",
        back: "ASCII is a character set that maps binary values to characters. Standard ASCII uses 7 bits, giving 128 possible codes.",
      },
      {
        id: "extended-ascii",
        category: "Character Sets",
        front: "Why was extended ASCII introduced?",
        back: "Extended ASCII uses 8 bits to represent 256 combinations, allowing extra characters such as additional symbols.",
      },
      {
        id: "unicode",
        category: "Character Sets",
        front: "Why is Unicode useful?",
        back: "Unicode supports far more characters than ASCII, allowing text from many languages and symbol sets to be represented consistently.",
      },
      {
        id: "floating-point",
        category: "Floating Point",
        front: "Why is floating point representation used?",
        back: "Floating point representation is used to store real numbers with fractional parts, very large values, or very small values.",
      },
      {
        id: "mantissa-exponent",
        category: "Floating Point",
        front: "What do the mantissa and exponent do in floating point representation?",
        back: "The mantissa stores the significant digits, while the exponent tells the computer how far to move the binary point.",
      },
      {
        id: "normalised",
        category: "Floating Point",
        front: "How can you identify a normalised floating point number?",
        back: "A normalised two's complement mantissa starts with 01 for a positive number or 10 for a negative number.",
      },
      {
        id: "precision-range",
        category: "Floating Point",
        front: "What happens if the mantissa or exponent is increased?",
        back: "Increasing the mantissa improves precision. Increasing the exponent increases the range or size of values that can be represented.",
      },
    ],
  },
  {
    id: "cs-1-4-2",
    subject: "Computer Science",
    code: "1.4.2",
    title: "Data structures",
    source: "1.4.2 - Topic Notes.pptx",
    summary:
      "Arrays, tuples, lists, records, queues, graphs, trees, binary trees, pointers, vertices, edges, and data structure comparisons.",
    cards: [
      {
        id: "array",
        category: "Arrays",
        front: "What is an array?",
        back: "An array is an ordered data structure with indexed elements, usually of the same data type, stored in a fixed-size structure.",
      },
      {
        id: "contiguous",
        category: "Arrays",
        front: "What does contiguous mean in an array?",
        back: "Contiguous means the array elements are stored next to each other in memory.",
      },
      {
        id: "static-array",
        category: "Arrays",
        front: "Why are arrays described as static?",
        back: "An array usually has a fixed size once created, so elements can be updated but new positions cannot simply be appended at runtime.",
      },
      {
        id: "3d-array",
        category: "Arrays",
        front: "What is a 3D array?",
        back: "A 3D array is an indexed structure with three dimensions, often imagined as layers, rows, and columns.",
      },
      {
        id: "tuple",
        category: "Tuples",
        front: "What is a tuple?",
        back: "A tuple is an ordered fixed-size data structure that can contain mixed data types and is immutable.",
      },
      {
        id: "immutable",
        category: "Tuples",
        front: "What does immutable mean?",
        back: "Immutable means the data structure cannot be changed after it has been created.",
      },
      {
        id: "list",
        category: "Lists",
        front: "What is a list?",
        back: "A list is an ordered dynamic data structure accessed by index, where items can usually be added, removed, sorted, and searched.",
      },
      {
        id: "record",
        category: "Records",
        front: "What is a record?",
        back: "A record stores multiple values under one identifier, with named attributes that can have different data types.",
      },
      {
        id: "array-of-records",
        category: "Records",
        front: "Why use an array of records?",
        back: "An array of records stores many related records together so each record can be accessed by index and each field by attribute name.",
      },
      {
        id: "queue",
        category: "Queues",
        front: "What is a queue?",
        back: "A queue is a First In, First Out data structure where new items join the rear and items leave from the front.",
      },
      {
        id: "queue-pointers",
        category: "Queues",
        front: "What do the front and rear pointers do in a queue?",
        back: "The front pointer identifies the next item to remove, while the rear pointer identifies where the newest item has been added.",
      },
      {
        id: "queue-uses",
        category: "Queues",
        front: "Where are queues used?",
        back: "Queues are used in print queues, keyboard buffers, network buffers, and any situation where requests are processed in arrival order.",
      },
      {
        id: "graph",
        category: "Graphs",
        front: "What is a graph?",
        back: "A graph is a data structure made from vertices connected by edges.",
      },
      {
        id: "vertices-edges",
        category: "Graphs",
        front: "What are vertices and edges?",
        back: "Vertices are the data points or nodes in a graph. Edges are the links connecting pairs of vertices.",
      },
      {
        id: "graph-types",
        category: "Graphs",
        front: "How can graphs be classified?",
        back: "Graphs can be directed or undirected, weighted or unweighted, and may contain cycles.",
      },
      {
        id: "tree",
        category: "Trees",
        front: "What is a tree?",
        back: "A tree is a hierarchical data structure made of nodes connected by branches, starting from a root.",
      },
      {
        id: "tree-terms",
        category: "Trees",
        front: "What are root, child, branch, and leaf nodes?",
        back: "The root is the first node, children are sub-nodes, branches connect nodes, and leaves are nodes with no children.",
      },
      {
        id: "graph-tree",
        category: "Comparison",
        front: "How does a graph differ from a tree?",
        back: "Graphs can contain cycles and can be directed, undirected, or weighted. Trees are hierarchical, have a root, and do not contain cycles.",
      },
      {
        id: "binary-tree-insert",
        category: "Trees",
        front: "How is data added to a binary search tree?",
        back: "Start at the root, compare the new value, go left if it is smaller or right if it is larger, and insert when there is no next node.",
      },
      {
        id: "choose-structure",
        category: "Comparison",
        front: "What should guide the choice of data structure?",
        back: "Consider whether data must be ordered, searchable, mutable, fixed size, hierarchical, queued, or linked by relationships.",
      },
    ],
  },
  {
    id: "cs-1-4-3",
    subject: "Computer Science",
    code: "1.4.3",
    title: "Boolean algebra",
    source: "1.4.3 - Topic Notes.pptx",
    summary:
      "Logic gates, truth tables, Boolean expressions, Karnaugh maps, half and full adders, D-type flip-flops, and Boolean simplification laws.",
    cards: [
      {
        id: "and",
        category: "Logic Gates",
        front: "What does an AND gate output?",
        back: "An AND gate outputs 1 only when all of its inputs are 1.",
      },
      {
        id: "or",
        category: "Logic Gates",
        front: "What does an OR gate output?",
        back: "An OR gate outputs 1 when one or more of its inputs are 1.",
      },
      {
        id: "not",
        category: "Logic Gates",
        front: "What does a NOT gate do?",
        back: "A NOT gate has one input and outputs the opposite value, changing 1 to 0 or 0 to 1.",
      },
      {
        id: "xor",
        category: "Logic Gates",
        front: "How does XOR differ from OR?",
        back: "XOR outputs 1 when exactly one input is 1. Unlike OR, it outputs 0 when both inputs are 1.",
      },
      {
        id: "nand-nor",
        category: "Logic Gates",
        front: "What are NAND and NOR gates?",
        back: "NAND is NOT AND, so it inverts an AND output. NOR is NOT OR, so it inverts an OR output.",
      },
      {
        id: "logic-circuit",
        category: "Logic Circuits",
        front: "How should you work through a logic circuit?",
        back: "Follow the gates step by step, calculating each intermediate output before combining them to find the final output.",
      },
      {
        id: "truth-table-rows",
        category: "Truth Tables",
        front: "How many truth table rows are needed for n inputs?",
        back: "A truth table needs 2 to the power of n rows, where n is the number of inputs.",
      },
      {
        id: "truth-table-columns",
        category: "Truth Tables",
        front: "Why add extra columns to a truth table?",
        back: "Extra columns store intermediate outputs from parts of the logic circuit, making the final output easier to calculate accurately.",
      },
      {
        id: "truth-table-order",
        category: "Truth Tables",
        front: "How should truth table input combinations be written?",
        back: "Start with all zeros, then count upward in binary until every possible input combination has been listed.",
      },
      {
        id: "circuit-to-expression",
        category: "Expressions",
        front: "How do you convert a logic circuit into a Boolean expression?",
        back: "Identify the final output gate, split the circuit into smaller groups, write each group as an expression, then combine them.",
      },
      {
        id: "expression-to-circuit",
        category: "Expressions",
        front: "How do you convert a Boolean expression into a logic circuit?",
        back: "Find the main operator, divide the expression into bracketed groups, then draw the required gates for each group and connect them.",
      },
      {
        id: "precedence",
        category: "Expressions",
        front: "What operator order is useful when reading Boolean expressions?",
        back: "A helpful precedence order is NOT first, then XOR, then AND, then OR.",
      },
      {
        id: "k-map-purpose",
        category: "Karnaugh Maps",
        front: "Why are Karnaugh maps used?",
        back: "Karnaugh maps help simplify Boolean expressions by grouping adjacent 1s and removing variables that change within a group.",
      },
      {
        id: "k-map-groups",
        category: "Karnaugh Maps",
        front: "What grouping order should you look for in a Karnaugh map?",
        back: "Look for groups of 8 first, then groups of 4, then pairs, and finally isolated 1s.",
      },
      {
        id: "k-map-size",
        category: "Karnaugh Maps",
        front: "How does Karnaugh map group size affect the simplified expression?",
        back: "Larger groups remove more variables, so they usually create shorter, cleaner Boolean expressions.",
      },
      {
        id: "k-map-expression",
        category: "Karnaugh Maps",
        front: "How is a simplified Karnaugh map answer written?",
        back: "Write one Boolean term for each group, then join the terms with OR.",
      },
      {
        id: "half-adder",
        category: "Adders",
        front: "What does a half adder do?",
        back: "A half adder adds two input bits and produces two outputs: a sum bit and a carry bit.",
      },
      {
        id: "half-adder-limits",
        category: "Adders",
        front: "Why is a half adder not enough for multi-bit binary addition?",
        back: "A half adder only has two inputs, so it cannot accept a carry bit from the previous column.",
      },
      {
        id: "full-adder",
        category: "Adders",
        front: "What does a full adder add?",
        back: "A full adder adds two input bits plus a carry-in bit, producing a sum and carry-out.",
      },
      {
        id: "n-bit-addition",
        category: "Adders",
        front: "How are full adders used to add n-bit binary numbers?",
        back: "Multiple full adders are connected so the carry-out from one column becomes the carry-in for the next column.",
      },
      {
        id: "flip-flop",
        category: "Flip-Flops",
        front: "What is a flip-flop?",
        back: "A flip-flop is a sequential logic circuit that can store one bit and switch between states 0 and 1.",
      },
      {
        id: "d-type",
        category: "Flip-Flops",
        front: "When does a D-type flip-flop update its output?",
        back: "A positive edge-triggered D-type flip-flop updates its output only on the rising edge of the clock signal.",
      },
      {
        id: "flip-flop-memory",
        category: "Flip-Flops",
        front: "How can flip-flops be used as memory?",
        back: "Each flip-flop stores one bit. Connecting several flip-flops creates register memory, such as eight flip-flops for eight bits.",
      },
      {
        id: "de-morgan",
        category: "Simplification",
        front: "What do De Morgan's laws do?",
        back: "De Morgan's laws complement each term and swap OR with AND, or AND with OR, when simplifying a negated expression.",
      },
      {
        id: "commutative-associative",
        category: "Simplification",
        front: "What do the commutative and associative laws allow?",
        back: "The commutative law allows terms to change order. The associative law allows terms to be regrouped without changing the result.",
      },
      {
        id: "absorption",
        category: "Simplification",
        front: "What is the idea behind the absorption law?",
        back: "Absorption removes a redundant term when a simpler term already covers it, such as B OR (B AND C) simplifying to B.",
      },
    ],
  },
  {
    id: "cs-1-5-1",
    subject: "Computer Science",
    code: "1.5.1",
    title: "Computing related legislation",
    source: "1.5.1 - Topic Notes.pptx",
    summary:
      "Data Protection Act, Computer Misuse Act, Copyright Designs and Patents Act, Regulation of Investigatory Powers Act, personal data, subject access, copyright, surveillance, and privacy.",
    cards: [
      {
        id: "big-four",
        category: "Legislation",
        front: "What are the four major acts in this topic?",
        back: "Data Protection Act 1998, Computer Misuse Act 1990, Copyright Designs and Patents Act 1988, and Regulation of Investigatory Powers Act 2000.",
      },
      {
        id: "dpa",
        category: "Data Protection",
        front: "What does the Data Protection Act control?",
        back: "It controls how data about living people is stored, processed, protected, used, and accessed.",
      },
      {
        id: "personal-data",
        category: "Data Protection",
        front: "What is personal data?",
        back: "Personal data is data that can be linked to a living, identifiable person, including paper and computerised records.",
      },
      {
        id: "sar",
        category: "Data Protection",
        front: "What is a subject access request?",
        back: "A subject access request lets a person ask an organisation whether it uses or stores their personal data and request copies of it.",
      },
      {
        id: "dpa-principles",
        category: "Data Protection",
        front: "Give examples of Data Protection Act expectations.",
        back: "Data should be used for the stated purpose, kept securely, kept only as long as needed, and made accessible to the person it concerns.",
      },
      {
        id: "cma",
        category: "Computer Misuse",
        front: "What does the Computer Misuse Act make illegal?",
        back: "It makes unauthorised access, unauthorised access with intent to commit further crime, and unauthorised modification of computer material illegal.",
      },
      {
        id: "cma-examples",
        category: "Computer Misuse",
        front: "Give examples of Computer Misuse Act offences.",
        back: "Trying to log in without authorisation, spreading viruses, deleting data without permission, modifying data, and carrying out DDoS attacks.",
      },
      {
        id: "cma-difficulty",
        category: "Computer Misuse",
        front: "Why can Computer Misuse Act enforcement be difficult?",
        back: "The internet is global, attackers can hide their identity, and offenders may be in countries with different laws or prosecution processes.",
      },
      {
        id: "cdpa",
        category: "Copyright",
        front: "What does the Copyright, Designs and Patents Act protect?",
        back: "It protects creators' intellectual property, including books, music, video, and software, from unauthorised copying or redistribution.",
      },
      {
        id: "software-copying",
        category: "Copyright",
        front: "How can software companies discourage illegal copying?",
        back: "They may use licence keys, require a disc or account check, use dongles, or apply digital rights management.",
      },
      {
        id: "p2p",
        category: "Copyright",
        front: "Why is peer-to-peer file sharing relevant to copyright?",
        back: "P2P systems can distribute copyrighted music, video, or software without permission, which can breach copyright law.",
      },
      {
        id: "ripa",
        category: "Surveillance",
        front: "What does RIPA regulate?",
        back: "The Regulation of Investigatory Powers Act regulates surveillance, interception of communications, monitoring internet activity, and access to encryption keys by public bodies.",
      },
      {
        id: "ripa-justifications",
        category: "Surveillance",
        front: "What can justify surveillance under RIPA?",
        back: "Reasons include national security, preventing or detecting crime, public safety, protecting public health, and assessing or collecting tax.",
      },
      {
        id: "privacy-security",
        category: "Ethics",
        front: "What is the privacy versus security debate?",
        back: "Surveillance may help identify criminals or terrorists, but citizens may value privacy and distrust broad government monitoring.",
      },
    ],
  },
  {
    id: "cs-1-5-2",
    subject: "Computer Science",
    code: "1.5.2",
    title: "Moral and ethical issues",
    source: "1.5.2 - Moral and Ethical Issues.pptx",
    summary:
      "Workforce change, automated decisions, AI, environmental impact, internet censorship, monitoring behaviour, analysing personal information, piracy, offensive communications, and cultural design.",
    cards: [
      {
        id: "workforce",
        category: "Workforce",
        front: "How can increased computer use affect the workforce?",
        back: "It can create demand for digital skills, automate roles, change working patterns, improve productivity, and risk excluding people without digital access or training.",
      },
      {
        id: "automation",
        category: "Workforce",
        front: "What kinds of jobs are more vulnerable to automation?",
        back: "Routine, repetitive, predictable, or rule-based jobs are often easier to automate than work requiring empathy, creativity, judgement, or complex human interaction.",
      },
      {
        id: "skills-gap",
        category: "Workforce",
        front: "What is the digital skills gap?",
        back: "The digital skills gap is the difference between the computing skills employers need and the skills available in the workforce.",
      },
      {
        id: "automated-decisions",
        category: "Automated Decisions",
        front: "What are automated decisions?",
        back: "Automated decisions are decisions made by computer systems or algorithms, such as insurance pricing, job filtering, university applications, or credit checks.",
      },
      {
        id: "automated-risk",
        category: "Automated Decisions",
        front: "Why can automated decision-making be risky?",
        back: "It can use biased or incomplete data, affect people unfairly, lack transparency, and require extra data collection to validate decisions.",
      },
      {
        id: "filter-bubble",
        category: "Automated Decisions",
        front: "What is a filter bubble?",
        back: "A filter bubble occurs when algorithms show people content based on previous behaviour, narrowing what they see and potentially reinforcing beliefs.",
      },
      {
        id: "ai",
        category: "AI",
        front: "What is artificial intelligence?",
        back: "AI is the development of systems able to perform tasks normally requiring human intelligence, such as perception, speech recognition, decision-making, or translation.",
      },
      {
        id: "turing-test",
        category: "AI",
        front: "What is the Turing test?",
        back: "The Turing test considers whether a machine can produce responses indistinguishable from a human in conversation.",
      },
      {
        id: "chatbot",
        category: "AI",
        front: "What is a chatbot?",
        back: "A chatbot is software designed to simulate conversation with users, often using rules or AI to respond to prompts.",
      },
      {
        id: "ai-ethics",
        category: "AI",
        front: "Name common ethical issues in AI.",
        back: "Unemployment, inequality, bias, security, unintended consequences, loss of control, accountability, and whether intelligent machines deserve rights.",
      },
      {
        id: "energy-use",
        category: "Environment",
        front: "How can digital technology increase energy demand?",
        back: "More devices, data centres, networks, AI systems, and cryptocurrency mining require electricity and may increase fossil fuel use if energy is not renewable.",
      },
      {
        id: "e-waste",
        category: "Environment",
        front: "Why is e-waste an environmental issue?",
        back: "Short device lifespans create waste containing toxic materials, which may be sent to landfill or dismantled unsafely in poorer countries.",
      },
      {
        id: "positive-environment",
        category: "Environment",
        front: "How can technology help the environment?",
        back: "It can support renewable energy, environmental monitoring, disaster prediction, carbon measurement, wildlife tracking, and more efficient resource use.",
      },
      {
        id: "censorship",
        category: "Censorship",
        front: "What is internet censorship?",
        back: "Internet censorship restricts what information can be published or viewed online, often by governments, ISPs, or platforms.",
      },
      {
        id: "censorship-pros",
        category: "Censorship",
        front: "What are arguments for internet censorship?",
        back: "It can restrict harmful content, reduce access to illegal activity, protect copyright, limit misinformation, and improve online safety.",
      },
      {
        id: "censorship-cons",
        category: "Censorship",
        front: "What are arguments against internet censorship?",
        back: "It can restrict legitimate information, limit free speech, be politically abused, create cost, and raise questions about who decides what is acceptable.",
      },
      {
        id: "monitoring",
        category: "Monitoring",
        front: "What behaviour can computers monitor?",
        back: "CCTV, phone calls, GPS location, emails, messages, browsing activity, purchases, and movement patterns can all be monitored.",
      },
      {
        id: "monitoring-debate",
        category: "Monitoring",
        front: "Why is monitoring behaviour ethically complex?",
        back: "It may help prevent crime and improve services, but it can invade privacy, create chilling effects, and concentrate power over personal data.",
      },
      {
        id: "personal-info",
        category: "Personal Data",
        front: "Why do organisations analyse personal information?",
        back: "They analyse data for services, marketing, credit scoring, medical treatment, fraud detection, recommendation systems, and business decisions.",
      },
      {
        id: "medicine",
        category: "Personal Data",
        front: "How can medical data analysis be beneficial?",
        back: "It can support personalised medicine, better diagnosis, population health research, and improved treatment planning.",
      },
      {
        id: "piracy",
        category: "Piracy",
        front: "What is digital piracy?",
        back: "Digital piracy is the unauthorised copying, sharing, streaming, or use of copyrighted content such as films, music, books, or software.",
      },
      {
        id: "offensive",
        category: "Communications",
        front: "What are offensive communications?",
        back: "Offensive communications include online threats, trolling, and messages intended to cause distress, often handled through communications law and platform rules.",
      },
      {
        id: "culture",
        category: "Culture",
        front: "Why do culture and language matter in software design?",
        back: "Different cultures may read in different directions, use different character sets, and interpret colours or icons differently.",
      },
      {
        id: "character-sets",
        category: "Culture",
        front: "Why can incompatible character sets cause problems?",
        back: "If a system cannot represent required characters, names, languages, or symbols may display incorrectly or become unusable.",
      },
    ],
  },
];
